### ISSUE TITLE
Stream with `reset: true` gets erased with `put_flash`

### ISSUE THREAD

**Issue by cjbottaro** [phoenixframework/phoenix_live_view#2623] opened 2023-05-10 19:53 UTC
I'm using `main` (dc4c139092c8b5eb6617ba9c9c6266853011c88e) with the new stream reset functionality. When I call `put_flash`, my stream disappears.

```elixir
def render(assigns) do
  ~H"""
  <.link class="btn btn-primary btn-sm w-40" phx-click="new">New</.link>

  <div class="overflow-x-auto">
    <table class="table w-full">
      <thead>
        <th>Name</th>
        <th>Created</th>
      </thead>
      <tbody id="project-list" phx-update="stream">
        <%= for {id, project} <- @streams.projects do %>
          <tr id={id} class="hover cursor-pointer" phx-click="project-selected" phx-value-id={project.id}>
            <td><%= project.name %></td>
            <td><%= time_ago(project.inserted_at) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  """
end

def mount(_params, _session, socket) do
  %{current_user: user} = socket.assigns

  user = Repo.preload(user, :projects)

  socket = socket
  |> stream(:projects, [])
  |> stream(:projects, user.projects, reset: true)

  {:ok, socket}
end

def handle_event("new", _params, socket) do
  socket = put_flash(socket, :info, "test")
  {:noreply, socket}
end
```

In the browser, all the users' projects appear in the table, but when you click on the button/link that triggers the flash message, all the projects disappear off the page.

Thanks for the help!

**Comment by chrismccord** [comment] 2023-05-11 00:08
The issues not put_flash. Any assign/diff will do, and it is caused by the following:

```elixir
  |> stream(:projects, [])
  |> stream(:projects, user.projects, reset: true)
```

I will take a deep look how we handle this case in a bit. Thanks!

**Comment by chrismccord** [comment] 2023-05-11 13:03
Fixed on main. Thank you!

**Closed** 2023-05-12 17:13 UTC
