### ISSUE TITLE
"no uploads have been allowed" when rendering component inside another component

### ISSUE THREAD

**Issue by thiagomajesk** [phoenixframework/phoenix_live_view#3284] opened 2024-06-05 02:06 UTC
Hi! I stumbled upon a strange behavior while creating an upload component. It seems that when I render a component inside another component, the allow upload doesn't work properly for some reason. 

I'm not sure if this is similar to https://github.com/phoenixframework/phoenix_live_view/issues/2708 or not, but here's a small repro: https://github.com/thiagomajesk/upload_component_repro.

Go to this LiveView here: `live "/upload", UploadLive` and check the code. You will see that the first upload component works because it's rendered directly inside the LiveView. However, when I have another component (like a form component) rendering the upload component inside of it, it doesn't work because it raises `no uploads have been allowed`. 

I'm running this with Elixir 1.16.2 (compiled with Erlang/OTP 26).

**Comment by balexand** [comment] 2024-06-05 23:07
It looks like you are rendering an HTML `<form>` element (in `AvatarUploadComponent`) within another `<form>` element (in `FormComponent`). Rendering a form in a form is invalid HTML and I wouldn't expect this to work correctly (see https://stackoverflow.com/a/379622/239965). Uploads work within nested LiveComponents as long as there are not nested `<form>` elements.

**Comment by SteffenDE** [comment] 2024-06-06 12:20
@thiagomajesk indeed your issue is caused by nested forms as @balexand already mentioned.

You should first ask yourself if the upload should actually be part of the parent form, i.e. that is is submitted together. In that case you'd probably call `allow_upload` in the LiveView directly.
If it should indeed be separate from the parent form, you could either try to simply move the upload outside of the parent form, or - that's probably not so pretty - rely on the HTML5 input's form attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#form

```
<.form id="myform" phx-change="..." phx-submit="..." /> 

<...>
  <.input ... form="myform" />

  <.live_component module={AvatarUploadComponent} />
</...>
```

As long as there are no nested `<form>` elements, the browser is happy and everything should work as expected.

Maybe we can do a better job of warning users about this. Recently we added a warning about having `<input name="id">` which will also cause problems clientside.

**Comment by thiagomajesk** [comment] 2024-06-06 17:48
Hi guys, thanks for jumping into this. I did not know that having nested forms was *invalid* HTML until you mentioned (I ended up finding some more information about it [here](https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form#:~:text=Warning%3A%20It%27s%20strictly%20forbidden%20to%20nest%20a%20form%20inside%20another%20form.%20Nesting%20can%20cause%20forms%20to%20behave%20unpredictably%2C%20so%20it%20is%20a%20bad%20idea))... My assumption was that you could potentially have some weird behavior if the form actually does something independently (which makes sense), but since uploads require a form for validating the upload (as far as my understanding goes); I'm unsure what would be the alternative. 

So, help me figure this out real quick...

My initial idea was to have a `<.input type="upload" />` that fills a hidden form field will a pre-signed URL so the parent form saves everything in one go. Of course, the parent is blocked until the upload finishes to prevent breaking the experience.

Having this configuration at the LV level is a no-go for me because the component should be "generic" and self-contained. Ideally, it should be possible to do the upload without a form (I haven't tested this to be honest); but I agree that the error message is not intuitive at all.

**Comment by thiagomajesk** [comment] 2024-06-08 15:53
A quick update on this:

I was taking a closer look at the code today and I don't think the problem is necessarily related to just having "nested forms"... If you replace the nested form with a simple `div` you'll still get the same exception, so something is off. 

I also looked at the client code as I thought that could be causing some weird behavior with submitting nested forms, but the uploader code doesn't even get called in this case.

The exception comes with the uploads  key not existing in the socket when the component is nested for some reason:

```
(phoenix_live_view 0.20.14) lib/phoenix_live_view/upload.ex:195: Phoenix.LiveView.Upload.get_upload_by_ref!/2  
(phoenix_live_view 0.20.14) lib/phoenix_live_view/channel.ex:1353: anonymous fn/3 in Phoenix.LiveView.Channel.maybe_update_uploads/2
```

https://github.com/phoenixframework/phoenix_live_view/blob/37bcbc4515efbedd3e85b3c0fbd39c4f88cea9f7/lib/phoenix_live_view/channel.ex#L1349-L1360

https://github.com/phoenixframework/phoenix_live_view/blob/37bcbc4515efbedd3e85b3c0fbd39c4f88cea9f7/lib/phoenix_live_view/upload.ex#L194-L198

**Comment by SteffenDE** [comment] 2024-06-08 18:16
@thiagomajesk I tried you reproduction but I cannot reproduce it.

If I comment the `simple_form` in your FormComponent (-> the AvatarComponent is directly rendered inside the root div of the FormComponent) it works exactly the same as the AvatarComponent rendered directly in the LV.

Does the form with the upload input inside maybe target another component (phx-target) than where you are calling `allow_upload`? Just guessing. I have to say that I'm not an export on LV uploads.

**Comment by thiagomajesk** [comment] 2024-06-08 19:16
Hi again @SteffenDE! Yes, if you replace or remove the outmost form, it does work because as you noticed, we are just rendering the component inside the parent LV...

Now, go to `AvatarUploadComponent` and replace the `form` with a `div` so you don't have nested forms (by removing the innermost form) and you'll get the exception too.

This is why I mentioned that I don't think the problem is exactly having nested forms, although I agree that this could create some weird behavior. I also did not investigate the LV code further to see why the assign is not getting passed to the socket.

**Comment by SteffenDE** [comment] 2024-06-08 19:30
I'm pretty sure that you must call `allow_upload` in the LV that handles the form events. If you don't render the `<form>` in the AvatarUploadComponent, the events are sent to the `FormComponent`. And then the error message is right again, there's no upload allowed.

So yes, you're right that the issue is not necessarily caused by nested forms. It is caused by sending form events to a target (LV or LC) that has no allowed the upload. In the initial example this is an inadvertent effect of nested forms, as the browser simply discards the inner form. The event is therefore sent to the `FormComponent`, but it hasn't allowed the upload. This is actually exactly the same as in your other case, just that you are not rendering the inner form that would be discarded by the browser. In the end, the rendered DOM is the same.

I guess the docs should be clearer about this. The only way to have a standalone upload component is to render it with its own form to handle the form events.

**Comment by thiagomajesk** [comment] 2024-06-08 20:28
Ok, I think I understand what is happening now and this went completely over my head. When you mentioned that you can't have nested forms, I didn't know that the browser actually doesn't render the innermost form to begin with...

So, if you don't have a form on `AvatarUploadComponent`, the `validate` event is sent to just `FormComponent` which makes sense, since is the first form it can find. If you do have a form though, event if it's not rendered, the validate event is sent twice - first to `AvatarUploadComponent` and then to `FormComponent`. I just tested that by adding a `handle_event` for the `validate` message on both components and I saw the CID in the exception was referring to the `FormComponent`. 

So yes, what you are saying makes sense... Either way, I think there's at least a couple DX improvements here to improve on the principle of least surprise. Also, it would be great if we could do something to make uploads more isolated when dealing with forms.

**Comment by josevalim** [comment] 2024-06-14 15:55
Closing this as I don't believe it is a LiveView issue. :)

I agree the behaviour can catch people by surprise, but it is ultimately a browser behaviour, and it is not possible for us to detect two separate components are rendering one form inside the other. Perhaps the client could track some of those, but checking for those on every patch would have rendering consequences on all applications.

**Closed by josevalim** 2024-06-14 15:55 UTC

**Comment by thiagomajesk** [comment] 2024-06-15 13:37
Hi @josevalim! What about the events being triggered twice even though the browser did not render the nested form?

**Comment by SteffenDE** [comment] 2024-06-15 14:08
@thiagomajesk I think this is because of form recovery. It doesn't happen with the changes from https://github.com/phoenixframework/phoenix_live_view/pull/3201.
