### ISSUE TITLE
LiveView.HTMLFormatter adds trailing newlines to ~H"" on Windows

### ISSUE THREAD

**Issue by FeeJai** [phoenixframework/phoenix_live_view#2167] opened 2022-09-01 00:13 UTC
### Environment

* Elixir version (elixir -v):  Elixir 1.13.4 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): phoenix 1.6.11 (Hex package) (mix)
* Phoenix LiveView version (mix deps): phoenix_live_view 0.17.11 (Hex package) (mix)
* Operating system: Windows 11
* Browsers you attempted to reproduce this bug on (the more the merrier): n/a
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: n/a

### Actual behavior
when running mix format, trailing new lines are added within sigils that include heex (e.g. ~H"<p></p>") 

### Expected behavior
No trailing new lines, as implemented here: https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/html_formatter.ex#L235

Works as designed on my Linux machine as well as on my mac

**Comment by josevalim** [comment] 2022-09-01 05:46
I cannot reproduce this. Can you please double confirm your Elixir version on Windows?

**Comment by ChickenPollo** [comment] 2022-09-13 16:55
Hello @josevalim here is the demonstration in my terminal including all the versions. 

```
PS C:\Users\luisd\source\repos\Elixir\advocrm> elixir -v
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit]

Elixir 1.13.3 (compiled with Erlang/OTP 22)
PS C:\Users\luisd\source\repos\Elixir\advocrm> Get-ComputerInfo OsName,OsVersion,OsBuildNumber,OsHardwareAbstractionLayer,WindowsVersion

OsName                     : Microsoft Windows 11 Education
OsVersion                  : 10.0.22000
OsBuildNumber              : 22000
OsHardwareAbstractionLayer : 10.0.22000.778
WindowsVersion             : 2009


PS C:\Users\luisd\source\repos\Elixir\advocrm> mix deps
* bcrypt_elixir 3.0.1 (Hex package) (mix)
  locked at 3.0.1 (bcrypt_elixir) 486bb95e
  ok
* bunt 0.2.0 (Hex package) (mix)
  locked at 0.2.0 (bunt) 7af5c7e0
  ok
* castore 0.1.18 (Hex package) (mix)
  locked at 0.1.18 (castore) 61bbaf64
  ok
* certifi 2.9.0 (Hex package) (rebar3)
  locked at 2.9.0 (certifi) 266da46b
  ok
* codepagex 0.1.6 (Hex package) (mix)
  locked at 0.1.6 (codepagex) 15214610
  ok
* comeonin 5.3.3 (Hex package) (mix)
  locked at 5.3.3 (comeonin) 3e38c9c2
  ok
* connection 1.1.0 (Hex package) (mix)
  locked at 1.1.0 (connection) 722c1eb0
  ok
* cowboy 2.9.0 (Hex package) (rebar3)
  locked at 2.9.0 (cowboy) 2c729f93
  ok
* cowboy_telemetry 0.4.0 (Hex package) (rebar3)
  locked at 0.4.0 (cowboy_telemetry) 7d98bac1
  ok
* cowlib 2.11.0 (Hex package) (rebar3)
  locked at 2.11.0 (cowlib) 2b3e9da0
  ok
* credo 1.6.6 (Hex package) (mix)
  locked at 1.6.6 (credo) 625520ce
  ok
* dart_sass 0.5.0 (Hex package) (mix)
  locked at 0.5.0 (dart_sass) bb769381
  ok
* db_connection 2.4.2 (Hex package) (mix)
  locked at 2.4.2 (db_connection) 4fe53ca9
  ok
* decimal 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (decimal) 34666e9c
  ok
* ecto 3.8.4 (Hex package) (mix)
  locked at 3.8.4 (ecto) f9244288
  ok
* ecto_sql 3.8.3 (Hex package) (mix)
  locked at 3.8.3 (ecto_sql) 348cb17f
  ok
* elixir_make 0.6.3 (Hex package) (mix)
  locked at 0.6.3 (elixir_make) f5cbd651
  ok
* esbuild 0.5.0 (Hex package) (mix)
  locked at 0.5.0 (esbuild) f183a0b3
  ok
* ex_aws 2.1.9 (Hex package) (mix)
  locked at 2.1.9 (ex_aws) 3e6c7767
  ok
* ex_aws_s3 2.3.3 (Hex package) (mix)
  locked at 2.3.3 (ex_aws_s3) 0044f0b6
  ok
* file_system 0.2.10 (Hex package) (mix)
  locked at 0.2.10 (file_system) 41195edb
  ok
* gettext 0.20.0 (Hex package) (mix)
  locked at 0.20.0 (gettext) 1c03b177
  ok
* hackney 1.18.1 (Hex package) (rebar3)
  locked at 1.18.1 (hackney) a4ecdaff
  ok
* idna 6.1.1 (Hex package) (rebar3)
  locked at 6.1.1 (idna) 92376eb7
  ok
* jason 1.3.0 (Hex package) (mix)
  locked at 1.3.0 (jason) 53fc1f51
  ok
* metrics 1.0.1 (Hex package) (rebar3)
  locked at 1.0.1 (metrics) 69b09add
  ok
* mime 2.0.3 (Hex package) (mix)
  locked at 2.0.3 (mime) 27a30bf0
  ok
* mimerl 1.2.0 (Hex package) (rebar3)
  locked at 1.2.0 (mimerl) f2785856
  ok
* parse_trans 3.3.1 (Hex package) (rebar3)
  locked at 3.3.1 (parse_trans) 07cd9577
  ok
* phoenix 1.6.11 (Hex package) (mix)
  locked at 1.6.11 (phoenix) 1664e34f
  ok
* phoenix_ecto 4.4.0 (Hex package) (mix)
  locked at 4.4.0 (phoenix_ecto) 09864e55
  ok
* phoenix_html 3.2.0 (Hex package) (mix)
  locked at 3.2.0 (phoenix_html) 36ec97ba
  ok
* phoenix_live_dashboard 0.6.5 (Hex package) (mix)
  locked at 0.6.5 (phoenix_live_dashboard) ef4fa50d
  ok
* phoenix_live_reload 1.3.3 (Hex package) (mix)
  locked at 1.3.3 (phoenix_live_reload) 76679667
  ok
* phoenix_live_view 0.17.11 (Hex package) (mix)
  locked at 0.17.11 (phoenix_live_view) 71777919
  ok
* phoenix_pubsub 2.1.1 (Hex package) (mix)
  locked at 2.1.1 (phoenix_pubsub) 81367c6d
  ok
* phoenix_view 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (phoenix_view) 7ae90ad2
  ok
* plug 1.13.6 (Hex package) (mix)
  locked at 1.13.6 (plug) 02b9c6b9
  ok
* plug_cowboy 2.5.2 (Hex package) (mix)
  locked at 2.5.2 (plug_cowboy) ea6e87f7
  ok
* plug_crypto 1.2.3 (Hex package) (mix)
  locked at 1.2.3 (plug_crypto) b5672099
  ok
* postgrex 0.16.4 (Hex package) (mix)
  locked at 0.16.4 (postgrex) 3234d1a7
  ok
* ranch 1.8.0 (Hex package) (rebar3)
  locked at 1.8.0 (ranch) 49fbcfd3
  ok
* sentry 8.0.6 (Hex package) (mix)
  locked at 8.0.6 (sentry) 051a2d04
  ok
* ssl_verify_fun 1.1.6 (Hex package) (mix)
  locked at 1.1.6 (ssl_verify_fun) bdb0d247
  ok
* sweet_xml 0.7.3 (Hex package) (mix)
  locked at 0.7.3 (sweet_xml) e110c867
  ok
* swoosh 1.7.4 (Hex package) (mix)
  locked at 1.7.4 (swoosh) 1553d994
  ok
* telemetry 1.1.0 (Hex package) (rebar3)
  locked at 1.1.0 (telemetry) b727b2a1
  ok
* telemetry_metrics 0.6.1 (Hex package) (mix)
  locked at 0.6.1 (telemetry_metrics) 7be9e087
  ok
* telemetry_poller 1.0.0 (Hex package) (rebar3)
  locked at 1.0.0 (telemetry_poller) b3a24eaf
  ok
* unicode_util_compat 0.7.0 (Hex package) (rebar3)
  locked at 0.7.0 (unicode_util_compat) 25eee6d6
  ok
* waffle 1.1.6 (Hex package) (mix)
  locked at 1.1.6 (waffle) deecbf20
  ok
* waffle_ecto 0.0.11 (Hex package) (mix)
  locked at 0.0.11 (waffle_ecto) 626c2832
  ok
* zarex 1.0.3 (Hex package) (mix)
  locked at 1.0.3 (zarex) 4400a7d3
  ok
PS C:\Users\luisd\source\repos\Elixir\advocrm> git status
HEAD detached at 195ec45
nothing to commit, working tree clean
PS C:\Users\luisd\source\repos\Elixir\advocrm> mix format
PS C:\Users\luisd\source\repos\Elixir\advocrm> git status
HEAD detached at 195ec45
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   lib/advocrm_web/templates/communication/subindex.html.heex
        modified:   lib/advocrm_web/views/contact_view.ex

no changes added to commit (use "git add" and/or "git commit -a")
PS C:\Users\luisd\source\repos\Elixir\advocrm> git diff
diff --git a/lib/advocrm_web/templates/communication/subindex.html.heex b/lib/advocrm_web/templates/communication/subindex.html.heex
index 5e04559..9ce9de2 100644
--- a/lib/advocrm_web/templates/communication/subindex.html.heex
+++ b/lib/advocrm_web/templates/communication/subindex.html.heex
@@ -25,7 +25,8 @@ <h2>Gesprächsnotizen</h2>
           <td><%= communication.content %></td>
           <td class="text-end">
             <%= if communication.document_count > 0 do %>
-              <%= link(~H"<i class=\"bi bi-paperclip\"></i>",
+              <%= link(~H"<i class=\"bi bi-paperclip\"></i>
+",
                 to:
                   Routes.contact_communication_document_path(
                     @conn,
diff --git a/lib/advocrm_web/views/contact_view.ex b/lib/advocrm_web/views/contact_view.ex
index 4956063..16bf5e6 100644
--- a/lib/advocrm_web/views/contact_view.ex
+++ b/lib/advocrm_web/views/contact_view.ex
@@ -12,26 +12,32 @@ def assigned_user(user_list, user_id) do
   def priority(assigns) do
     case assigns.contact.priority do
       :low ->
-        ~H"<span class=\"text-success\"><i class=\"bi bi-thermometer-low\"></i></span>"
+        ~H"<span class=\"text-success\"><i class=\"bi bi-thermometer-low\"></i></span>
+"

       :average ->
-        ~H"<span class=\"text-warning\"><i class=\"bi bi-thermometer-half\"></i></span>"
+        ~H"<span class=\"text-warning\"><i class=\"bi bi-thermometer-half\"></i></span>
+"

       :high ->
-        ~H"<span class=\"text-danger\"><i class=\"bi bi-thermometer-high\"></i></span>"
+        ~H"<span class=\"text-danger\"><i class=\"bi bi-thermometer-high\"></i></span>
+"
     end
   end

   def priority_text(assigns) do
     case assigns.contact.priority do
       :low ->
-        ~H"<span class=\"text-success\">Niedrig</span>"
+        ~H"<span class=\"text-success\">Niedrig</span>
+"

       :average ->
-        ~H"<span class=\"text-warning\">Mittel</span>"
+        ~H"<span class=\"text-warning\">Mittel</span>
+"

       :high ->
-        ~H"<span class=\"text-danger\">Hoch</span>"
+        ~H"<span class=\"text-danger\">Hoch</span>
+"
     end
   end

@@ -110,7 +116,8 @@ def pagination(assigns) do
       </nav>
       """
     else
-      ~H""
+      ~H"
+"
     end
   end
 end
```

**Comment by josevalim** [comment] 2022-09-13 16:59
@ChickenPollo It is fixed on Elixir v1.13.4. :)

**Closed by josevalim** 2022-09-13 16:59 UTC

**Comment by ChickenPollo** [comment] 2022-09-13 17:08
Thank you @josevalim unfortunetely 1.13.4 is not available through Chocolatey. @OnorioCatenacci, can you upgrade the source? 
Thank you.

**Comment by OnorioCatenacci** [comment] 2022-09-13 17:12
I was working on getting 1.14.0 up to CNG the other day but I ran into a
minor issue.

**Comment by josevalim** [comment] 2022-09-13 17:49
You can also run the [installer](https://github.com/elixir-lang/elixir-windows-setup/releases/download/v2.2/elixir-websetup.exe) or scoop on Windows if you prefer!
