### ISSUE TITLE
Some containers do not receive the `phx-no-feedback` class even though they have the `phx-feedback-for` properly defined

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#3071] opened 2024-02-01 12:28 UTC
### Environment

* Elixir version (elixir -v): 1.14.4
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps): 0.20.1 `b2c8999aaccf07509bf2f119f7a23d14269bfa26` vs `bed2ff05bb024b2927fb9c1523e42ca55627715f` "Speed up patching 5-10x (#2845)"
* Operating system: Linux Mint
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, FF
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Some elements (containers in `phx-feedback-for` parlance) no longer receive the `phx-no-feedback` class when they should i.e. when the `phx-feedback-for` is present with the proper form field name.

I've tried hard to detect the pattern i.e. to find in what way these elements are defined differently than those that still receive the class but so far without success - meaning that at this moment I can't write a demo app replicating this, that is for as long as I can't tell what I am supposed to replicate. 

So far I've tried the following (both isolated and in combo with others) and no combo managed to circumvent the bug :
- removing the element id
- render element unconditionally
- make the element class a static string (as opposed to composed dynamically)
- make the `phx-feedback-for` unconditional static string (as opposed conditioned by the assigns)

I've noticed the bug first when migrated from 0.20.1 to 0.20.3 and then dived into finding the exact commit. If starting from checking out `b2c8999aaccf07509bf2f119f7a23d14269bfa26` which is the last commit without the bug , the bug will not manifest until the "Bump build" in `5a3368da026ea011c2f6790bdd7045ce216402ec` but when going in reverse it will be there in  `bed2ff05bb024b2927fb9c1523e42ca55627715f ` where the relevant changes to `phoenix_live_view.js` were first made.

### Expected behavior

All elements with the `phx-feedback-for` attribute properly set should receive the `phx-no-feedback` class.

**Comment by SteffenDE** [comment] 2024-02-01 12:36
Hi, have you tried the latest main? There were some changes recently concerning the phx-no-feedback handling that are not released yet.
If it happens there as well we'd need some minimal example to reproduce. https://github.com/wojtekmach/mix_install_examples/blob/main/phoenix_live_view.exs is a good starting point. Thank you!

**Comment by josevalim** [comment] 2024-02-01 13:08
@DaTrader you should be able to reproduce it by yanking elements from the page and the LiveView, one by one while the error occurs, until it stays minimal, and then copy that to the single file app. :)

**Comment by SteffenDE** [comment] 2024-02-01 13:22
Just an idea, but maybe it's an escaping problem of the feedback names; can you try the following?

```
{:phoenix_live_view, github: "SteffenDE/phoenix_live_view", branch: "escape_feedback_names_assets", override: true}
```

**Comment by DaTrader** [comment] 2024-02-01 15:05
> Just an idea, but maybe it's an escaping problem of the feedback names; can you try the following?

Unfortunately, it's not.

**Comment by DaTrader** [comment] 2024-02-01 15:06
> @DaTrader you should be able to reproduce it by yanking elements from the page and the LiveView, one by one while the error occurs, until it stays minimal, and then copy that to the single file app. :)

I'm going to try, although it's always the same elements that don't receive the class.

**Comment by DaTrader** [comment] 2024-02-01 17:58
Ok, I found what it takes to replicate the bug. It's the presence of the new `data-phx-id` in a `<.input type="hidden"/>`. 

The form element in question (the one that won't receive `phx-no-feedback`) is the parent the element for which I am using the following function component added to `CoreComponents`:

```
def input( %{ type: "hidden"} = assigns) do
  ~H"""
  <input
    type={@type}
    name={@name}
    id={@id}
    value={Phoenix.HTML.Form.normalize_value(@type, @value)}
    {@rest}
  />
  """
end
```

This overrides the default `<.input type="hidden"/>` which would otherwise end up wrapping up the input field into a container with a label, the opinionated styling and errors which I found unnecessary. Besides, all this is not so important because I tried your default `CoreComponents` implementation and it does not work either.

So, in my case the following is the problematic child of the element that should have received the `phx-no-feedback`:

```
<.input type="hidden" field={@post_form[:media_url]}/>
```

rendering as:

```
<input data-phx-id="ResourceLive-115" type="hidden" name="post_composition[media_url]" id="post_composition_media_url">
```

which does not work. However, if I replace the component with the rendered code but without the `data-phx-id`, it does work again:

```
<input type="hidden" name="post_composition[media_url]" id="post_composition_media_url">
```

The thing is I prefer to keep on leveraging the ` field` attribute and not resolve the name and the id manually for hidden inputs.

**Comment by chrismccord** [comment] 2024-02-01 18:13
When you trigger the bug, what does the DOM look like for the input element?

**Comment by DaTrader** [comment] 2024-02-01 18:15
As I wrote above:

```
<input data-phx-id="ResourceLive-115" type="hidden" name="post_composition[media_url]" id="post_composition_media_url">
```

**Comment by chrismccord** [comment] 2024-02-01 18:18
Can you wrap this up in a minimal reproduction? Tracing our code right now it's not clear to me how to reproduce the issue. Thanks!

**Comment by DaTrader** [comment] 2024-02-01 18:20
Ok, will do it tomorrow (now it's getting late on the side of the world :)

**Comment by chrismccord** [comment] 2024-02-01 18:38
I haven't reproduced, but I have a guess on what might be the cause. Can you try the `cm-fix-feedback` branch? Thanks!

**Comment by DaTrader** [comment] 2024-02-01 18:51
I hate to break the party, but now I see it works only in one case. The other is still not working properly.

Will study it now to see what's different

**Comment by DaTrader** [comment] 2024-02-01 18:58
Ok, the first difference I can see is that in this other case the `<.input type="hidden"/> is a child of a button that is a child of the element that should have received the `phx-no-feedback`, so no longer a direct child.

**Comment by DaTrader** [comment] 2024-02-02 08:09
Just upgraded to 0.20.4 and this last issue with a non-direct child is still there. 

The first one with a direct child stays fixed - thank you for that.

**Comment by chrismccord** [comment] 2024-02-02 09:08
Yeah 0.20.4 only has the partial fix. If you can provide a repro it would really help me fully solve it. Thanks!

**Comment by DaTrader** [comment] 2024-02-02 09:21
I am going to. Currently I am trying to pinpoint yet another client-side bug that was introduced post 0.20.3. When I report that issue, I'll get on the repros for this one and the other one I reported a couple of days ago.

**Comment by DaTrader** [comment] 2024-02-02 14:14
> Hi, have you tried the latest main? There were some changes recently concerning the phx-no-feedback handling that are not released yet. If it happens there as well we'd need some minimal example to reproduce. https://github.com/wojtekmach/mix_install_examples/blob/main/phoenix_live_view.exs is a good starting point. Thank you!

Do you have a working single file example with Tailwind?

**Comment by SteffenDE** [comment] 2024-02-02 15:27
```elixir
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7.0"},
  {:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main", override: true}
])

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.HomeLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  def mount(_params, _session, socket) do
    {:ok, assign(socket, :count, 0)}
  end

  defp phx_vsn, do: Application.spec(:phoenix, :vsn)
  defp lv_vsn, do: Application.spec(:phoenix_live_view, :vsn)

  def render("live.html", assigns) do
    ~H"""
    <script src={"https://cdn.jsdelivr.net/npm/phoenix@#{phx_vsn()}/priv/static/phoenix.min.js"}></script>
    <script src={"https://cdn.jsdelivr.net/gh/phoenixframework/phoenix_live_view@main/priv/static/phoenix_live_view.min.js"}></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }
    </style>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""
    <%= @count %>
    <button phx-click="inc" class="bg-blue-500 text-white p-4">+</button>
    <button phx-click="dec" class="bg-blue-500 text-white p-4">-</button>
    """
  end

  def handle_event("inc", _params, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count + 1)}
  end

  def handle_event("dec", _params, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count - 1)}
  end
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/", HomeLive, :index)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)
  plug(Example.Router)
end

{:ok, _} = Supervisor.start_link([Example.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)
```

There you go

**Comment by SteffenDE** [comment] 2024-02-02 16:19
can you try
```
{:phoenix_live_view, github: "SteffenDE/phoenix_live_view", branch: "fix_skipped_feedback_assets", override: true}
```

I think that we found the root cause.

**Comment by DaTrader** [comment] 2024-02-02 16:55
Nope. The ancestor element in question is still not receiving the `phx-no-feedback`.

**Comment by SteffenDE** [comment] 2024-02-02 17:12
Ok thank you. Just to be sure, can you quickly try `{:phoenix_live_view, github: "SteffenDE/phoenix_live_view", branch: "development", override: true}`?

**Comment by DaTrader** [comment] 2024-02-02 17:17
Just did. Still the same issue.

Btw, now I am trying to reproduce it and it's not easy because it wants me reproduce more surrounding behavior than I thought (like in the original app). Hopefully, I'll manage to finish this today. If not then Monday.

**Comment by SteffenDE** [comment] 2024-02-02 17:21
No worries. Thank you for the effort!

**Comment by SteffenDE** [comment] 2024-02-02 17:32
Last try. If it doesn't work with this I'm not sure how it ever worked earlier...

```
{:phoenix_live_view, github: "SteffenDE/phoenix_live_view", branch: "brute_force_track_inputs", override: true}
```

This is not a proper fix, but basically forces all input elements to be tracked.

**Comment by DaTrader** [comment] 2024-02-02 17:44
You nailed it

**Comment by DaTrader** [comment] 2024-02-02 17:45
Should I continue with the repro demo app or you know what you need to do now?

**Comment by DaTrader** [comment] 2024-02-02 17:53
Btw, it may have to do with multiple inputs referencing the same form field. This is something this component has that other don't.

**Comment by chrismccord** [comment] 2024-02-02 19:35
@DaTrader can you try this PR? https://github.com/phoenixframework/phoenix_live_view/pull/3081

If that doesn't work, I'll need your reproduction to dig further. Note that Steffens brute-force fix was just a sanity check on our part. It's too expensive for us to perform in that way so I'm hoping #3081 solve it for you. Thanks!

**Comment by SteffenDE** [comment] 2024-02-03 10:08
Please also test:
```
{:phoenix_live_view, github: "SteffenDE/phoenix_live_view", branch: "apply_feedback_permanently_assets", override: true}
```

**Comment by DaTrader** [comment] 2024-02-03 10:36
The #3081 PR does not work, but the latest @SteffenDE suggestion does!!

**Comment by SteffenDE** [comment] 2024-02-03 11:23
How does the input that you use when you remove media_url look like? Does the form have a phx-change binding? Does it trigger when you remove the media_url?

**Comment by DaTrader** [comment] 2024-02-03 11:52
`phx-change` is set at the form level and it triggers when I remove the `media_url`.

**Comment by ahallock** [comment] 2024-02-04 14:38
heads up: 0.20.4 throws a JS error when inputs are not contained within the form; ie, using the input `form` attribute. This occurs on the phx-submit event:

```
    <div>
      <.form id={@form.id} for={@form} phx-change="validate" phx-submit="create" phx-target={@myself}>
        <.button type="submit">Submit</.button>
      </.form>

      <div phx-feedback-for={@form[:name].name}>
        <input
          type="text"
          form={@form.id}
          name={@form[:name].name}
          id={@form[:name].id}
          value={Phoenix.HTML.Form.normalize_value("text", @form[:name].value)}
        />
        <.error field={@form[:name]} />
      </div>
    </div>
```

```
dom.js:305 Uncaught TypeError: Cannot read properties of null (reading 'elements')
    at dom.js:305:23
```

**Comment by SteffenDE** [comment] 2024-02-04 14:39
@ahallock should be already fixed on main via https://github.com/phoenixframework/phoenix_live_view/commit/a222c7fb8cb459089b13250a42c069b6d34a71ad

**Comment by ahallock** [comment] 2024-02-04 14:54
@SteffenDE you're right. Thank you!

**Comment by SteffenDE** [comment] 2024-02-05 16:12
@DaTrader I changed the LV script to

```
<script src={"https://cdn.jsdelivr.net/gh/SteffenDE/phoenix_live_view@apply_feedback_permanently_assets/priv/static/phoenix_live_view.min.js"}></script>
```

And the white border stays white.

**Comment by SteffenDE** [comment] 2024-02-05 16:14
The same happens with
```
<script src={"https://cdn.jsdelivr.net/gh/SteffenDE/phoenix_live_view@extract_feedback_assets/priv/static/phoenix_live_view.min.js"}></script>
```

that you can try in your main app using
```
{:phoenix_live_view, github: "SteffenDE/phoenix_live_view", branch: "extract_feedback_assets", override: true}
```

**Comment by DaTrader** [comment] 2024-02-05 16:34
Yes, but then that other thing does not work - the one I mentioned here: https://github.com/phoenixframework/phoenix_live_view/issues/3071#issuecomment-1925268383

**Comment by DaTrader** [comment] 2024-02-05 16:43
The problem is that in that other case you keep the `phx-no-feedback` even after there's no longer the `phx-feedback-for` attribute.

**Comment by SteffenDE** [comment] 2024-02-05 17:12
Ah I think I understand the problem. Will work on a fix 👍🏻

**Comment by SteffenDE** [comment] 2024-02-05 17:39
@DaTrader please try the `extract_feedback_assets` or `apply_feedback_permanently_assets` branches (hopefully both should work now).

**Comment by DaTrader** [comment] 2024-02-05 17:47
`extract_feedback_assets` works, while the other one does not. 

`apply_feedback_permanently_assets` introduces a behavior that is even worse than before - as soon as the second case form is open the field shows an error even if nothing was entered or clicked on.

**Comment by SteffenDE** [comment] 2024-02-05 17:53
Interesting. They should basically do the same thing. I'm happy to hear that the `extract_feedback_assets` branch works as this is the direction we probably want to go.

**Comment by DaTrader** [comment] 2024-02-05 17:55
So can you make a PR?

**Comment by SteffenDE** [comment] 2024-02-05 18:26
https://github.com/phoenixframework/phoenix_live_view/pull/3086

**Comment by DaTrader** [comment] 2024-02-07 15:11
@chrismccord @SteffenDE 

Guys, this issue has not been fixed by the PR. Just run the single demo app and you'll see it for yourself.

**Comment by DaTrader** [comment] 2024-02-07 15:15
@SteffenDE Why haven't you PR-ed just the `extract_feedback_assets` for that one did work properly?

**Comment by SteffenDE** [comment] 2024-02-07 15:15
@DaTrader sorry about that, it was closed automatically because the PR was merged.

> apply_feedback_permanently_assets introduces a behavior that is even worse than before - as soon as the second case form is open the field shows an error even if nothing was entered or clicked on.

How can I reproduce this? The single file example does not show this as far as I can see? Using `    <script src={"https://cdn.jsdelivr.net/gh/SteffenDE/phoenix_live_view@apply_feedback_permanently_assets/priv/static/phoenix_live_view.js"}></script>` in there seems to work fine?

**Comment by SteffenDE** [comment] 2024-02-07 15:16
> Why haven't you PR-ed just the `extract_feedback_assets` for that one did work properly?

Chris wants to wait before merging this because phx-feedback-for will be removed in one of the next releases.

**Comment by DaTrader** [comment] 2024-02-07 15:17
Common guys, when is the end to the breaking changes?

**Comment by SteffenDE** [comment] 2024-02-07 15:19
> Common guys, when is the end to the breaking changes?

The answer is: when LiveView reaches 1.0. For this change there will also be a drop in solution for existing applications, no worries. And we will of course make sure that it works the way that it should.

**Comment by josevalim** [comment] 2024-02-07 15:20
@DaTrader when 1.0 is out, by definition.

However, the goal is to also give developers a snippet that keeps phx-feedback-for functionality if they want to.

**Comment by DaTrader** [comment] 2024-02-07 15:25
> How can I reproduce this? The single file example does not show this as far as I can see? Using ` <script src={"https://cdn.jsdelivr.net/gh/SteffenDE/phoenix_live_view@apply_feedback_permanently_assets/priv/static/phoenix_live_view.js"}></script>` in there seems to work fine?

@SteffenDE This JS works. Can you please make a commit that has this script within a dep so I don't need to update apps in two different places?

**Comment by DaTrader** [comment] 2024-02-07 15:27
> Chris wants to wait before merging this because phx-feedback-for will be removed in one of the next releases.

Also, this makes me wonder why we spent so much time on this bug in the first place (i.e. you could've told me that before)?

**Comment by josevalim** [comment] 2024-02-07 15:29
Because these problems were the catalyst for looking for a new solution. If you believe you have put much time, please consider how much time we have put too, developing, maintaining, and fixing these bugs.

Also note that,whenever we introduce a new approach, we do our best to keep the old ways working for quite some time to ease migration. If you prefer, we can just introduce the new approach and yank the old permanently forever. It would definitely be less work on our side.

**Comment by SteffenDE** [comment] 2024-02-07 15:30
> @SteffenDE This JS works. Can you please make a commit that has this script within a dep so I don't need to update apps in two different places?

@DaTrader 0.20.5 will be released soon (probably today), please try this one first, it will include the exact code that is present in the script from apply_feedback_permanently_assets.

**Comment by DaTrader** [comment] 2024-02-07 15:40
> Because these problems were the catalyst for looking for a new solution.

Well, I didn't know that. 

> If you believe you have put much time, please consider how much time we have put too, developing, maintaining, and fixing these bugs.

I have never questioned that.  The point is very simple here. If you know you're going to discard/completely change something, please advertise the decision in advance so we (the LV users) can make our decisions accordingly.

> If you prefer, we can just introduce the new approach and yank the old permanently forever.

Is there a way to gain access to these observations and decisions as soon as they happen? I believe I asked this once before and was referred to "what was (or will be) said on a conference x". Do you have a chatroom or something where you discuss these things?

**Comment by DaTrader** [comment] 2024-02-07 15:42
@josevalim Speaking of which, can you tell me _now_ what the `phx-feedback-for` will be substituted with in a future release?

**Comment by josevalim** [comment] 2024-02-07 15:43
> If you know you're going to discard/completely change something, please advertise the decision in advance so we (the LV users) can make our decisions accordingly.

Because, as said above, "whenever we introduce a new approach, we do our best to keep the old ways working for quite some time to ease migration".

> Is there a way to gain access to these observations and decisions as soon as they happen?

Yes, the issues tracker. Following Phoenix and LiveView should be enough. In this case: https://github.com/phoenixframework/phoenix/pull/5713

**Comment by josevalim** [comment] 2024-02-07 15:50
> If you know you're going to discard/completely change something, please advertise the decision in advance so we (the LV users) can make our decisions accordingly.

As said above, "whenever we introduce a new approach, we do our best to keep the old ways working for quite some time to ease migration". Plus you *have* been told in advance. The feature is in a pull request for everyone to see and it has not been merged yet.

> Is there a way to gain access to these observations and decisions as soon as they happen?

Yes, the issues tracker. Following Phoenix and LiveView should be enough. In this case: https://github.com/phoenixframework/phoenix/pull/5713

**Comment by SteffenDE** [comment] 2024-02-08 14:00
@DaTrader 0.20.5 is out now :)

**Comment by DaTrader** [comment] 2024-02-08 14:53
@SteffenDE Unfortunately, the bug has not been fixed but worsened as previously mentioned here: https://github.com/phoenixframework/phoenix_live_view/issues/3071#issuecomment-1927592412.

This indicates that it wasn't `extract_feedback_asset` (that does work) that was applied but `apply_feedback_permanently_assets` (or both?)

**Comment by SteffenDE** [comment] 2024-02-08 16:11
> How can I reproduce this? The single file example does not show this as far as I can see? Using ` <script src={"https://cdn.jsdelivr.net/gh/SteffenDE/phoenix_live_view@apply_feedback_permanently_assets/priv/static/phoenix_live_view.js"}></script>` in there seems to work fine?

I still cannot reproduce what you describe. I'm using your single file example and changed the dependency to 0.20.5 and the script tag to use LiveView main. If I type into the field and then on the invisible button the border stays white. If I click the invisible button without typing into the field, the border stays white. I cannot get the border to become red.

**Comment by DaTrader** [comment] 2024-02-08 16:57
PS. The v0.20.5 does have its "bump build"

**Comment by DaTrader** [comment] 2024-02-08 17:05
Ok. Now I am not following any more.

I have the following dependency in the `Mix.install` call: `  {:phoenix_live_view, "0.20.5", override: true}` and the following link script link (by default): `<script src={"https://cdn.jsdelivr.net/gh/phoenixframework/phoenix_live_view@main/priv/static/phoenix_live_view.min.js"}></script>`

The above does not work.

However, if when I replace the script with the one you just provided again, it does work. Shouldn't this script that you provided and that works be in the v0.20.5 by default i.e. without the need to link it additionally?

**Comment by SteffenDE** [comment] 2024-02-08 17:09
Can you describe what "does not work" mean? (LV 0.20.5 should be equal to apply_feedback_permanently_assets)

**Comment by DaTrader** [comment] 2024-02-08 17:12
The single file app does not work (the border turns red after entering something in the white text field and clicking the invisible button) with the default script, but works with the one you just re-quoted: `<script src={"https://cdn.jsdelivr.net/gh/SteffenDE/phoenix_live_view@apply_feedback_permanently_assets/priv/static/phoenix_live_view.js"}></script>`

They are obviously not the same.

**Comment by DaTrader** [comment] 2024-02-08 17:16
To summarize it in a single comment..

Does not work: `<script src={"https://cdn.jsdelivr.net/gh/phoenixframework/phoenix_live_view@main/priv/static/phoenix_live_view.min.js"}></script>`

Works: `<script src={"https://cdn.jsdelivr.net/gh/SteffenDE/phoenix_live_view@apply_feedback_permanently_assets/priv/static/phoenix_live_view.js"}></script>`

Meaning: they are not the same thing

**Comment by SteffenDE** [comment] 2024-02-08 17:21
https://github.com/phoenixframework/phoenix_live_view/assets/4116351/96a94a30-d1b4-45fc-8685-e0dd8653b27d

Well, then something else must be going on, as I still cannot reproduce this. As you can see in the video I am using LV 0.20.5 and the script from main. The border does not get red. I tried this in Arc (Chromium) and Safari.
Maybe you still get a cached version of the old script from main? Can you try to download the file directly from GitHub and use it locally (e.g. place the content directly in the script tag)

**Comment by SteffenDE** [comment] 2024-02-08 17:47
If you can send a new reproduction I'll be happy to take another look. Currently I have no clue what could still be wrong, sorry :(

**Comment by DaTrader** [comment] 2024-02-08 17:48
Yeah, I guess I'll have to.

**Comment by DaTrader** [comment] 2024-02-15 11:33
@SteffenDE 

> Can you describe what "does not work" means? (LV 0.20.5 should be equal to apply_feedback_permanently_assets)

I found the difference between the two and why it works on v0.20.1 and not on v0.20.5+. 

The reason is that on v0.20.1 (your `{ :phoenix_live_view,  github: "SteffenDE/phoenix_live_view", branch: "0.20.1_fixes", override: true}`) the `phx-no-feedback` was still automatically added to all elements with the `phx-feedback-for` attribute even if nothing's been entered in the form yet, while in the single app demo that only seems to work (because of the border color) it isn't so until something is entered and then only when LV detects first some input.  In my real app, this is a problem because I set one of the form values programmatically which used to work on your v0.20.1 fix because it unquestionably obeyed the `phx-feedback-for` attribute while the v0.20.5+ does not.

Start the single file demo app and inspect the relevant `data-its-this-one` element and you'll see it does not have the `phx-no-feedback` class added by default (despite the `phx-feedback-for` attribute.

**Closed** 2024-02-15 14:51 UTC

**Comment by SteffenDE** [comment] 2024-02-15 14:54
@DaTrader you can try the fix with
```
    <script src={"https://cdn.jsdelivr.net/gh/SteffenDE/phoenix_live_view@feedback_node_added_assets/priv/static/phoenix_live_view.min.js"}></script>
```

or 

```
{:phoenix_live_view, github: "SteffenDE/phoenix_live_view", branch: "feedback_node_added_assets", override: true}
```

**Comment by DaTrader** [comment] 2024-02-15 15:13
@SteffenDE It works finally. Well done!
