### ISSUE TITLE
Render of a LV into a <thead> element renders incorrectly

### ISSUE THREAD

**Issue by gregjohnsonsaltaire** [phoenixframework/phoenix_live_view#132] opened 2019-03-27 04:16 UTC
```
    ~L"""
      <table>
         <thead><%= live_render(@socket, HeaderLive) %></thead>
      </table>
    """
```

After socket connection, the render of a LV into a `<thead>` element renders incorrectly into the "id" `<div>` instead of the `<thead>` element.

The initial disconnected render renders correctly into the `<thead>` element.

Code to replicate the issue is at the end of this report.

### Environment

* Elixir version (elixir -v): Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.8.0 (compiled with Erlang/OTP 20)
* Phoenix version (mix deps): {:phoenix, github: "phoenixframework/phoenix", branch: "v1.4", override: true}
* Phoenix Live_View version (mix deps): {:phoenix_live_view, github: "phoenixframework/phoenix_live_view"}
* NodeJS version (node -v): v11.9.0
* NPM version (npm -v): 6.9.0
* Operating system: macOS 10.14.4

### Actual behavior
Connected:
![Screen Shot 2019-03-27 at 13 32 18](https://user-images.githubusercontent.com/4063838/55046203-d0349680-5094-11e9-86af-326105d2eb57.png)
```
<div id="phx-QQn9WXNEKLM=" data-phx-view="DemoWeb.TableLive"
    data-phx-session="SFMyNTY ..." class="phx-connected">
    <div id="phx-QQn9WXNEKLM=:DemoWeb.TableLive.HeaderLive" data-phx-parent-id="phx-QQn9WXNEKLM="
        data-phx-view="DemoWeb.TableLive.HeaderLive"
        data-phx-session="SFMyNTY ..." conn="" class="phx-connected">
        -A--B--C-
    </div>
    <div class="phx-loader" style="display: none;"></div>
    <table style="width:100%"><thead></thead></table>
</div>
```
Disconnected:
![Screen Shot 2019-03-27 at 13 31 58](https://user-images.githubusercontent.com/4063838/55046212-d88cd180-5094-11e9-8ffe-d4c4c05f2431.png)
```
<div id="phx-gUOSoTdukGQ=" data-phx-view="DemoWeb.TableLive"
    data-phx-session="SFMyNTY ..." class="phx-disconnected">
    <div id="phx-gUOSoTdukGQ=:DemoWeb.TableLive.HeaderLive" data-phx-parent-id="phx-gUOSoTdukGQ="
        data-phx-view="DemoWeb.TableLive.HeaderLive"
        data-phx-session="SFMyNTY ...">
    </div>
    <div class="phx-loader"></div>
    <table style="width:100%"><thead><tr><th>A</th><th>B</th><th>C</th></tr></thead></table>
</div>
```

### Expected behavior
Connected:
![Screen Shot 2019-03-27 at 13 31 58](https://user-images.githubusercontent.com/4063838/55046212-d88cd180-5094-11e9-8ffe-d4c4c05f2431.png)
```
<div id="phx-QQn9WXNEKLM=" data-phx-view="DemoWeb.TableLive"
    data-phx-session="SFMyNTY ..." class="phx-connected">
    <div id="phx-QQn9WXNEKLM=:DemoWeb.TableLive.HeaderLive" data-phx-parent-id="phx-QQn9WXNEKLM="
        data-phx-view="DemoWeb.TableLive.HeaderLive"
        data-phx-session="SFMyNTY ..." conn="" class="phx-connected">
    </div>
    <div class="phx-loader" style="display: none;"></div>
    <table style="width:100%"><thead><tr><th>A</th><th>B</th><th>C</th></tr></thead></table>
</div>
```
Disconnected:
![Screen Shot 2019-03-27 at 13 31 58](https://user-images.githubusercontent.com/4063838/55046212-d88cd180-5094-11e9-8ffe-d4c4c05f2431.png)
```
<div id="phx-gUOSoTdukGQ=" data-phx-view="DemoWeb.TableLive"
    data-phx-session="SFMyNTY ..." class="phx-disconnected">
    <div id="phx-gUOSoTdukGQ=:DemoWeb.TableLive.HeaderLive" data-phx-parent-id="phx-gUOSoTdukGQ="
        data-phx-view="DemoWeb.TableLive.HeaderLive"
        data-phx-session="SFMyNTY ...">
    </div>
    <div class="phx-loader"></div>
    <table style="width:100%"><thead><tr><th>A</th><th>B</th><th>C</th></tr></thead></table>
</div>
```
### Code to replicate Issue
```
defmodule DemoWeb.TableLive do
  use Phoenix.LiveView

  defmodule HeaderLive do
    def render(assigns) do
      ~L"""
        <tr><th>-A-</th><th>-B-</th><th>-C-</th></tr>
      """
    end

    def mount(_session, socket) do
      {:ok, socket}
    end
  end

  def render(assigns) do
    if assigns.socket.connected?, do: :timer.sleep(2000)

    ~L"""
      <table style="width:100%"><thead><%= live_render(@socket, HeaderLive) %></thead></table>
    """
  end

  def mount(_session, socket) do
    {:ok, socket}
  end
end
```

**Comment by sionide21** [comment] 2019-03-27 17:59
What if a LiveView provided a callback to specify a tagname that defaults to `div`?

Then it could look something like:

```
defmodule HeaderLive do

  def tagname(), do: "thead"

  ...
end
```

and the template could change to

```
~L"""
  <table>
     <%= live_render(@socket, HeaderLive) %>
  </table>
"""
```

**Comment by josevalim** [comment] 2019-03-28 09:41
Duplicate of #128.

**Closed by josevalim** 2019-03-28 09:41 UTC
