### ISSUE TITLE
When creating a dynamic form, the code is essentially the same, but the behavior differs.

### ISSUE THREAD

**Issue by nallwhy** [phoenixframework/phoenix_live_view#3074] opened 2024-02-02 09:36 UTC
### Environment

* Elixir version (elixir -v): 1.16.1
* Phoenix version (mix deps): 26.2.1
* Phoenix LiveView version (mix deps): 0.20.4
* Operating system: Mac
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

I created two checkboxes for adding a new input in a dynamic form: one directly and the other using a component. The directly created checkbox adds an input and then gets unchecked without any issues, but the checkbox created using a component does not get unchecked after adding an input, leading to the continuous addition of new inputs whenever the content changes.

You can reproduce it with the code below.

https://github.com/nallwhy/phoenix_dynamic_form_bug

```elixir
defmodule DynamicFormWeb.Live do
  ...

  @impl true
  def render(assigns) do
    ~H"""
    <.simple_form for={@person_form} phx-change="validate">
      <.input label="name" field={@person_form[:name]} />
      <.inputs_for :let={fc} field={@person_form[:contracts]}>
        <.field_adder_hidden for={fc} name="person[contracts_sort][]" />
        <.input label="file name" field={fc[:file_name]} />
        <.label>
          <input type="checkbox" name="person[contracts_drop][]" value={fc.index} /> remove
        </.label>
      </.inputs_for>

      <input type="hidden" name="person[contracts_drop][]" />

      # checkbox 1
      <label class="block cursor-pointer">
        <input type="checkbox" name="person[contracts_sort][]" /> add more1
      </label>

      # checkbox 2
      <.field_adder name="person[contracts_sort][]" label="add more2" />
    </.simple_form>
    """
  end

  ...

  attr(:name, :string, required: true)
  attr(:label, :string, default: nil)

  def field_adder(assigns) do
    ~H"""
    <label class="block cursor-pointer">
      <input type="checkbox" name={@name} />
      <%= @label %>
    </label>
    """
  end
end
```

<img width="759" alt="image" src="https://github.com/phoenixframework/phoenix_live_view/assets/4961183/3a0abc3c-9729-452b-b815-8e588c6a898b">

I tried to reproduce it based on https://github.com/wojtekmach/mix_install_examples/blob/main/phoenix_live_view.exs, but it its not reproduced in that way.

### Expected behavior

The checkbox created with a component should also become unchecked after adding an input.

**Comment by SteffenDE** [comment] 2024-02-02 09:52
Duplicate of https://github.com/phoenixframework/phoenix_live_view/issues/3056.

See my comment over there and also the updated guide: https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#inputs_for/1-dynamically-adding-and-removing-inputs

The dom patching is optimized and with checkboxes you rely on a discrepancy between client side and server side state. If you want to keep using checkboxes ensure that the function component changes when patched, for example by using a rolling id.

Thank you!

**Closed by SteffenDE** 2024-02-02 09:52 UTC
