### ISSUE TITLE
mailto: and tel: links in a LiveView cause an unload despite no navigation occuring

### ISSUE THREAD

**Issue by dkulchenko** [phoenixframework/phoenix_live_view#2672] opened 2023-06-06 03:10 UTC
### Environment

* Elixir version (elixir -v): 1.14.4
* Phoenix version (mix deps): 1.7.3
* Phoenix LiveView version (mix deps): 0.18.18
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Safari, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

ref https://github.com/phoenixframework/phoenix_live_view/issues/2552#issuecomment-1547215797

```html
<a href="mailto:a@example.com">Contact support</a>
```

In my app, I have a contact support email link in the footer, similar to the above. Clicking the link causes the LiveView to unload, even though navigation away from the page is not occurring. 

### Expected behavior

mailto:/tel: links should not unload the socket/destroy hooks.

**Comment by dkulchenko** [comment] 2023-06-06 03:14
Given https://github.com/phoenixframework/phoenix_live_view/issues/2552#issuecomment-1546997948, it seems like unload should be suppressed entirely unless the link is an http:/https: absolute link or a relative link (/a/b).

**Comment by rktjmp** [comment] 2023-06-06 17:32
`mailto:` is fixed in 0.19. `tel:` still causes a remount on my linux/ffx install, but that may be a quirk of not having a handler configured as the code for tel exists https://github.com/phoenixframework/phoenix_live_view/blob/0058afeab2f2ad500b7285368c639a0d7bf8f2a0/assets/js/phoenix_live_view/dom.js#L77

Irregular protocols still cause the dismount, 0.19.1 added some code that can sort of mitigate it by calling `preventDefault` but you then need to manually relocate the browser, and it also causes a view remount. Without the mitigation it disconnects the view without updating the appropriate phx-connected class on the view.

<details>

```elixir
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7.2"},
  {:phoenix_live_view, "~> 0.19.1"}
])

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.HomeLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  def mount(_params, _session, socket) do
    {:ok, assign(socket, :count, 0)}
  end

  def render("live.html", assigns) do
    ~H"""
    <script src="https://cdn.jsdelivr.net/npm/phoenix@1.7.2/priv/static/phoenix.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/phoenix_live_view@0.19.1/priv/static/phoenix_live_view.min.js"></script>
    <script>
      let Hooks = {}
      Hooks.NoDisconnect = {
        mounted() {
          this.el.addEventListener("click", e => {
            e.preventDefault()
            window.location.href = e.target.href
          })
        }
      }
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket, {hooks: Hooks})
      liveSocket.connect()
      setInterval(() => {
        const c = liveSocket.isConnected()
        document
          .querySelectorAll("#connected-indicator")
          .forEach(el => el.setAttribute("socket-connected", c))
      }, 200)
    </script>
    <style>
      * { font-size: 1.1em; }

      #connected-indicator::after { content: attr(socket-connected); }
      #connected-indicator[socket-connected=false]{ color: red; }
      #connected-indicator[socket-connected=true]{ color: green; }

      .indicator { color: red; }
      .indicator::after{ content: ' .phx-connected not present'; }
      .phx-connected .indicator { color: green; content: 'connected' }
      .phx-connected .indicator::after{ content: ' .phx-connected present'; }
    </style>

    <div id="connected-indicator" class="">liveSocket.isConnected() = </div>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""

    <div class="indicator">.phx-connected .indicator -> </div>

    <a href="tel:000000">tel</a>
    <a href="mailto:000000">mailto</a>
    <a id="steam-link" phx-hook="NoDisconnect" href="steam://install/8230">Open Steam</a>

    <button phx-click="inc">send event <%= @count %></button>
    """
  end

  def handle_event("inc", params, socket) do
    {:noreply, assign(socket, :count, socket.assigns.count + 1)}
  end
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/", HomeLive, :index)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)
  plug(Example.Router)
end

{:ok, _} = Supervisor.start_link([Example.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)

```

</details>

**Comment by chrismccord** [comment] 2023-06-06 17:42
This is handled properly in 0.19.1. @rktjmp your reproduction works properly for me in all major browsers so I need more information. Please open a new issue if you can provide more details. Thanks!

**Closed by chrismccord** 2023-06-06 17:42 UTC

**Comment by rktjmp** [comment] 2023-06-06 18:12
> rktjmp your reproduction works properly for me in all major browsers so I need more information. 

Do you also mean the custom protocol link is behaving as you expect? eg. the intended process is:

1. catching the anchor click
1. calling `event.preventDefault`
1. manually redirecting the browser via `window.location.href`
1. having the liveview remount

**Comment by chrismccord** [comment] 2023-06-06 18:16
sorry the specific reproduction you linked contained only tel: and mailto:. If there are other custom protocols that are parsable valid urls, today you'll need to stopPropagation on them which will prevent it bubbling to window, but still allow default browser behavior afaik. I will look into limited navigation to only http/s

**Comment by rktjmp** [comment] 2023-06-06 18:26
In this thread it's the open steam link,

![image](https://github.com/phoenixframework/phoenix_live_view/assets/866010/45816cbe-ce50-472e-8429-e8118c2c9e49)

(In the original "download issue" it was a tailspire as described by another user.) Unsure of a good cross platform example of a non-standard protocol.

I think it probably makes most sense to whitelist as you say, unlikely that protocol list will grow much!
