### ISSUE TITLE
Input field getting stuck in a readonly state

### ISSUE THREAD

**Issue by samullen** [phoenixframework/phoenix_live_view#220] opened 2019-05-14 14:14 UTC
### Environment

* Elixir version:

Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.7.4 (compiled with Erlang/OTP 21)

* Phoenix version: 1.4.4
* NodeJS version: 9.4.0
* NPM version: 6.5.0
* Operating system: Mac and Linux

### Actual behavior

I have a page listing athletes for an event (race) with a search box to allow the user to quickly find specific athletes. If there are athletes registered for the race, they are displayed in a table with their relevant information. Otherwise a simple "hero" div is show explaining no athletes have registered.

When a user searches (i.e. enters a value in the search field and hits "Enter") for an athlete, the search hits the LiveView module and returns the results. If there are results, everything works as expected. If not, a hero div is show instead of the table of athletes with the following leex code:

```
<h3>No matching athletes found for "<%= @term %>".</h3>
```

If another search is performed with similarly negative results, the search field and hero output remain the same. However, if a subsequent search is performed wherein athletes are found, the `input_text` field is set to a "read only" state.

In the JS console of firefox, the following error is displayed: "TypeError: can't assign to property "dynamics" on "suzy": not an object"

The entire JS stacktrace from FF:

```
TypeError: can't assign to property "dynamics" on "suzy": not an object app.js line 104 > eval:1358:28
    e webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:1358
    e webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:1358
    e webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:1358
    e webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:1358
    mergeDiff webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:1355
    value webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:1799
    value webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:1879
    value webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:233
    forEach self-hosted:262
    value webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:232
    value webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:251
    value webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:410
    e webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:293
    value webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:410
    value webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:715
    decode webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:478
    value webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:705
    onmessage webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js?:536
```

If I change the hero output so it doesn't display the search term like so:

```
<h3>No matching athletes found.</h3>
```

Everything works as expected.

### Expected behavior

Based on the if/else logic, I expect athletes to be listed in the table and the hero to no longer display after a successful search.

### leex template

```
      <%= if Enum.empty?(@athletes) && @term == "" do %>
        <div class="card-body">
          <div class="jumbotron">
            <h3>No athletes have registered for this event.</h3>
          </div>
        </div>
      <% else %>
        <div class="card-body">
          <h4>Athletes</h4>

          <%= form_for %Ecto.Changeset{}, "#", [as: "search", phx_submit: "search"], fn f -> %>
            <div class="form-group">
              <%= text_input :search, :term, [class: "form-control", placeholder: "Search"] %>
              <small class="form-text text-muted">Search by name or email</small>
            </div>
          <% end %>
        </div>

        <%= if Enum.empty?(@athletes) do %>
          <div class="card-body">
            <div class="jumbotron">
              <h3>No matching athletes found for "<%= @term %>".</h3>
            </div>
          </div>
        <% else %>
          <table id="athlete-table" class="table table-hover table-sm">
            <thead>
              <th>Name</th>
              <th>Contact</th>
            </thead>

            <tbody>
              <%= for athlete <- @athletes do %>
                <tr>
                  <td>
                    <%= link lastname_first(athlete), to: athlete_path(CerberusWeb.Endpoint, :show, athlete.id) %> <small class="text-muted">(<%= athlete.gender %>)</small><br>
                    <small><%= datef(athlete.birth_date) %></small>
                  </td>
                  <td>
                    <%= link athlete.email, to: "mailto:#{athlete.email}" %><br>
                    <%= phones(athlete) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
```

I can publish the LiveView code as well if it's necessary, but I'd prefer not until I know it is.

As a side note, LiveView's been great to work with.

**Comment by chrismccord** [comment] 2019-05-15 16:43
This looks like a bug with our diff merging. If you could publish a complete LV + template that would be extremely helpful, especially if you can prune down the template. My guess is this is triggered by the nested if + for comprehension with the way we track diffs, but a reproducible example will let us know for sure. Thanks!

**Comment by samullen** [comment] 2019-05-15 20:40
Sure. Thanks, Chris.

The LiveView:

```elixir
defmodule CerberusWeb.EventLive do
  use Phoenix.LiveView

  import Ecto.Query, only: [from: 2]

  alias Cerberus.{Repo, Athlete, Event, TrifectaMetrics}

  def render(assigns) do
    CerberusWeb.EventView.render("show.html", assigns)
  end

  def mount(%{event_id: id, current_user: current_user, page: page}, socket) do
    event =
      Repo.get(Event, id)
      |> Repo.preload([:race, :event_category])
    trifecta_metrics = Cerberus.TrifectaMetrics.for_event(event)
    athletes =
      event_athletes(event)
      |> Repo.paginate(page: page)

    assigns =
      assignments(event, athletes)
      |> Map.merge(%{
        current_user: current_user,
        term: "",
        event: event,
        race: event.race,
        context: "event",
        completed_trifecta_count: trifecta_metrics[:completed_count],
        estimated_trifecta_count: trifecta_metrics[:estimated_count],
        trifecta_x_counts: trifecta_metrics[:trifecta_x_counts],
      })

    {:ok, assign(socket, assigns)}
  end

  def handle_event("event-loader", event_id, socket) do
    event = socket.assigns.event
    chronotrack_event_id = event.chronotrack_event_id

    if Cerberus.Loader.EventPublisher.add_event(chronotrack_event_id) == :ok do
      {:ok, event} =
        Ecto.Changeset.change(event)
        |> Repo.update(force: true)

      {:noreply, assign(socket, :event, event)}
    else
      {:noreply, socket}
    end
  end

  def handle_event("search", %{"search" => %{"term" => term}}, socket) when is_nil(term) or term == "" do
    event = socket.assigns.event
    athletes =
      event_athletes(event)
      |> Repo.paginate()

    assigns =
      assignments(event, athletes)
      |> Map.merge(%{term: ""})

    {:noreply, assign(socket, assigns)}
  end

  def handle_event("search", %{"search" => %{"term" => term}}, socket) do
    event = socket.assigns.event
    athletes =
      Cerberus.AthleteSearch.results(term)
      |> event_athletes(event)
      |> Repo.all()

    assigns =
      assignments(event, athletes)
      |> Map.merge(%{term: term})

    {:noreply, assign(socket, assigns)}
  end

  defp assignments(event, athletes) do
    %{
      athletes: athletes,
      athlete_summaries: athlete_summaries(athletes, event.starts_at.year),
    }
  end

  defp event_athletes(scope \\ Athlete, event) do
    from(a in scope,
      join: e in assoc(a, :entries),
      where: e.event_id == ^event.id,
      order_by: [asc: a.last_name, asc: a.first_name],
      preload: [entries: [event: :event_category]]
    )
  end

  defp athlete_summaries(athletes, year) do
    athletes
    |> Enum.into(
      %{},
      &{&1.id, Cerberus.AthleteProfile.trifecta_summary(&1, year)}
    )
  end
end
```

The pruned template. 

```eex
<nav aria-label="breadcrumb">
...
</nav>

<div class="row">
  <div class="col-md-4">
  <!-- side nav -->
  </div  

  <div class="col-md-8">
    <div class="card">
      <%= if Enum.empty?(@athletes) && @term == "" do %>
        <div class="card-body">
          <div class="jumbotron">
            <h3>No athletes have registered for this event.</h3>
          </div>
        </div>
      <% else %>
        <div class="card-body">
          <h4>Athletes</h4>

          <%= form_tag "#", [phx_submit: "search"] do %>
            <div class="form-group">
              <%= text_input :search, :term, [class: "form-control", placeholder: "Search"] %>
              <small class="form-text text-muted">Search by name or email</small>
            </div>
          <% end %>
        </div>

        <%= if Enum.empty?(@athletes) do %>
          <div class="card-body">
            <div class="jumbotron">
              <h3>No matching athletes found.</h3>
            </div>
          </div>
        <% else %>
          <table id="athlete-table" class="table table-hover table-sm">
            <thead>
              <th>Name</th>
              <th>Contact</th>
              <th>Victories</th>
            </thead>

            <tbody>
              <%= for athlete <- @athletes do %>
                <tr>
                  <td>
                    <%= link lastname_first(athlete), to: athlete_path(CerberusWeb.Endpoint, :show, athlete.id) %> <small class="text-muted">(<%= athlete.gender %>)</small><br>
                    <small><%= datef(athlete.birth_date) %></small>
                  </td>
                  <td>
                    <%= link athlete.email, to: "mailto:#{athlete.email}" %><br>
                    <%= phones(athlete) %>
                  </td>
                  <td class="text-center">
                    <span class="badge badge-danger">
                      <%= @athlete_summaries[athlete.id].sprint %>
                    </span>
                    <span class="badge badge-primary">
                      <%= @athlete_summaries[athlete.id].super %>
                    </span>
                    <span class="badge badge-success">
                      <%= @athlete_summaries[athlete.id].beast %>
                    </span>
                    <span class="badge badge-dark">
                      <%= @athlete_summaries[athlete.id].complete %>
                    </span>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <%= if is_nil(@term) || @term == "" do %>
            <div class="card-body">
              <!-- pagination -->
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
```

**Comment by DavidVII** [comment] 2019-05-22 19:23
I have a feeling this is somewhat connected to diffing issues from #160. I describe something similar [here](https://github.com/phoenixframework/phoenix_live_view/issues/160#issuecomment-488202863) and created a small app to help with reproducing: https://github.com/DavidVII/liveview-issues.

I'm using a select tag instead of a search field like described above, but it behaves similarly. If there are non-nil or non-empty results, everything seems to work fine, but when the value is nil that's when things start to act up.

**Comment by conradfr** [comment] 2019-07-04 14:28
Did you find a workaround ?

I also got a "TypeError: can't assign to property "dynamics" on "No data": not an object", where "No data" is just a text I print in a div whensome condition is not met.

Everything works great as long as I don't hit the else that prints the "No data".

**Comment by DavidVII** [comment] 2019-07-10 18:35
@conradfr Still no workaround. I remedy _some_ of the problem by manually setting the value and listening for changes, but it's still quite messy and doesn't behave as an input should. The repo I created above should make it easy to reproduce these issues, but I'm not sure how to go about fixing these issues.

**Comment by snewcomer** [comment] 2019-08-03 22:09
@DavidVII Really appreciate the reproduction 🙏.  Helped a lot in debugging.  Based on your repro, one option is you build a changeset with the `params` in your `handle_event/3` and assign to the socket.  Similar to what you do in `mount/2`.  

The next question is - why should this be necessary?  This is due to the reflective nature of `input` and the `value` attribute of that HTMLElement.  The `attribute` is the initial value and the `property` is the "live" value of the `input` and doesn't reflect itself back on the `attribute`.  As a result, when passing around a `string` representation of the live parts of your app (say the stringified `form`) between the client and server, the `property` is lost and can't be translated back to real HTML.

We have a few options:
1. phoenix input tags reflect the "live" value back on the attribute by default
2. document this behaviour.
3. manually manage all input "live" values.  e.g. When comparing two nodes, if the "live" `from` node value is different than the `to` node attribute, update the `to` node property with the `from` node property.

Let me know what you/others think!

(the other steps in your repro README seem to be solved with #178.  Let me know if that isn't the case)

**Comment by snewcomer** [comment] 2019-08-10 19:24
@samullen If you have a chance, mind checking to see if you still have an issue on master?  This may have been fixed with #291.  Sort of a guess though.

**Comment by samullen** [comment] 2019-08-16 12:44
Sorry, @snewcomer. Still seeing the same issue.

**Comment by snewcomer** [comment] 2019-08-17 06:35
Thanks Samuel!  If someone was able to put together a reproduction of the issue in a repo, I would be super grateful.  I've been debugging with the live_view [examples](https://github.com/chrismccord/phoenix_live_view_example) `search` route trying to match the snippets above with no luck.

**Comment by chrismccord** [comment] 2019-08-17 17:32
Please try latest master (make sure to blow away node_modules/phoenix_live_view) and report back. Thanks!

**Closed** 2019-08-17 17:33 UTC

**Comment by oskarkook** [comment] 2019-08-17 18:23
@chrismccord `priv/static/phoenix_live_view.js` is outdated:
```
var r=n[i],o=t[i];O(r)&&o?(O(o)&&o.dynamics&&!r.dynamics
```
