### ISSUE TITLE
Hooks in deadview don't run when live_render is present

### ISSUE THREAD

**Issue by ChristianAlexander** [phoenixframework/phoenix_live_view#2327] opened 2022-11-12 15:45 UTC
### Environment

* Elixir version (elixir -v): `1.14.0`
* Phoenix version (mix deps): `1.6.15`
* Phoenix LiveView version (mix deps): `0.18.3`
* Operating system: MacOS Monterey
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When a liveview is embedded on deadview page via `live_render`, hooks in the deadview no longer mount / run.

I've created a repository that demonstrates this issue: https://github.com/ChristianAlexander/deadview_live_render_hooks

### Expected behavior

Since this application is running a version of liveview greater than 0.18, I'd expect that all `phx-hook` attributes present on the page would be mounted, even when some of the page is live and other parts are dead.

I had initially though this might be related to #2314, but it's possible that `phx-click` is a different issue.

**Comment by LostKobrakai** [comment] 2022-11-16 21:49
I've just noticed the same behaviour with JS commands. Works fine on a plain deadview. Adding a (unrelated) `live_render` it stops to work.

**Comment by mxgrn** [comment] 2022-11-21 02:35
@LostKobrakai Exactly what's described in https://github.com/phoenixframework/phoenix_live_view/issues/2314, I suppose these 2 issues _are_ caused by the same root problem.

**Comment by chrismccord** [comment] 2022-11-28 18:18
closed via 1668849

**Closed by chrismccord** 2022-11-28 18:18 UTC
