### ISSUE TITLE
Clear multiple select in liveview test

### ISSUE THREAD

**Issue by maclover7** [phoenixframework/phoenix_live_view#1291] opened 2020-12-23 19:40 UTC
### Environment

* Elixir version (elixir -v): 1.11.2
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.0
* NodeJS version (node -v): 15.4.0
* NPM version (npm -v):
* Operating system: Mac
* Browsers you attempted to reproduce this bug on (the more the merrier): n/a
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

Attempting to clear a multiple select field in a liveview test but appear unable to do so. Here's my test scenario:

In the form:

```eex
<%= multiple_select f, :editors ... %>
```

In the test:

```elixir
{:ok, _, html} =
        index_live
        |> form("#story-form", story: { editors: [] })
        |> render_submit()
```

With this code, the `editors` attribute ends up becoming `[""]`

### Expected behavior

I'd expect setting `editors` to `[]` to clear the field and ensure it is empty when submitting the form. When submitting a multiple select with no items selected through the front end UI, the attribute is not included in the submit request to the server. Or, if not setting `editors` to `[]`, then `nil` might work. But unfortunately, setting to `nil` triggers this error: `** (ArgumentError) could not find non-disabled input, select or textarea with name "story[editors]"  ...`.

Looking for guidance about the proper API to clear this multiple select in the test.

**Comment by josevalim** [comment] 2020-12-23 19:41
I think we are treating an empty list the same as not sending anything... which means we end-up sending the default. It looks like a bug. :)

**Comment by mveytsman** [comment] 2020-12-29 04:33
@maclover7 I can't reproduce this issue in so far as tests behave the same way as the UI for me -- in both cases I don't see the attribute with the empty array in the params.  Do you mind providing a more complete example?

The underlying issue is that `Plug.Conn.Query.encode(%{foo: "a", bar: []}) == "foo=a"`. I know this leads to a lot of confusion but I don't think there's any way to send empty lists in URL parameters as they are implemented today.

@josevalim am I right that you mean the bug would be if tests behave differently than LiveView itself, or are you thinking we should make the unselected multiple select give you an empty list in the params?

**Comment by josevalim** [comment] 2020-12-29 07:04
> The underlying issue is that Plug.Conn.Query.encode(%{foo: "a", bar: []}) == "foo=a". 

I think this is the issue, right? If you can't send an empty select, then the default choice for the select (such as the prompt), will always be picked. Although maybe in this case you shouldn't have a prompt with multiple select? Yeah, more info would help.

**Comment by josevalim** [comment] 2021-06-21 13:56
Closing this per the above, thanks!

**Closed by josevalim** 2021-06-21 13:56 UTC
Labels: bug
