### ISSUE TITLE
Topbar displayed twice for different live sessions

### ISSUE THREAD

**Issue by wceolin** [phoenixframework/phoenix_live_view#2861] opened 2023-10-11 14:03 UTC
### Environment

* Elixir version (elixir -v): 1.15.5
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.20.0

### Actual behavior

When navigating to a different `live_session`, the topbar is displayed twice on the page because the page fully reloads. This feels a little bit weird because it looks like the topbar starts when the page actually finished loading already.

#### Steps to reproduce

- Clone this [repo](https://github.com/wceolin/topbar-example)
- Run `mix setup`.
- Run `mix phx.server`.
- Enable latency on the browser console: `liveSocket.enableLatencySim(1000)`.
- Navigate from the "home" page to the "posts" one: The topbar is displayed only one because it's the same `live_session`.
- Navigate from the "posts" page to the "dashboard" one: The topbar is displayed twice because it's a different `live_session`.

https://github.com/phoenixframework/phoenix_live_view/assets/4393133/d5fbe947-54a6-4749-b752-850e3a7b8d68

### Expected behavior

I'm not sure if this is a bug or expected behavior, actually. But, in my view, the topbar should be displayed only once. It should start when the navigation begins and stop when the page is fully loaded.

#### Workaround

Right now, I'm using a workaround to call `topbar.show` only when `info.detail.kind` is `redirect`. It prevents the topbar from being displayed twice, but I'm not sure that's the ideal solution.

#### Notes
I'm not sure if this is the right repo or if the `phoenix` one would be more appropriate.

**Comment by chrismccord** [comment] 2023-10-17 19:37
You can only live navigate within the same live session.  Your demo tries to live navigate (`<.link navigate`) across live sessions, which requires an extra round trip to the server and looks like the cause of your unwanted behavior. Regular link href is all you need here and it will not dispatch the loading event in that case, resolving the behavior you're seeing. Thanks!

**Closed by chrismccord** 2023-10-17 19:37 UTC

**Comment by wceolin** [comment] 2023-10-17 23:05
@chrismccord I see. Thank you for the explanation.
