### ISSUE TITLE
reconnect during upload

### ISSUE THREAD

**Issue by Nikolaycc** [phoenixframework/phoenix_live_view#2757] opened 2023-08-02 06:58 UTC
### Environment

* Elixir version (elixir -v): 1.15.4
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.19.5
* Operating system: Ubuntu
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

### Actual behavior
When I upload some file it reconnects

```html
<form id="upload-form" phx-submit="savee" phx-change="vali">
      <div class="container" phx-drop-target={@uploads.image.ref}>
            <.live_file_input upload={@uploads.image} />   
      </div>
      <button type="submit">Upload</button>
</form>
```

```exs
[error] GenServer #PID<0.547.0> terminating
** (KeyError) key "phx-F3d9rya2kNrrOwUD" not found in: %{"phx-F3d9ryLkHbHrOwTD" => :image}
    :erlang.map_get("phx-F3d9rya2kNrrOwUD", %{"phx-F3d9ryLkHbHrOwTD" => :image})
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/upload.ex:192: Phoenix.LiveView.Upload.get_upload_by_ref!/2
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:1218: anonymous fn/3 in Phoenix.LiveView.Channel.maybe_update_uploads/2
    (stdlib 5.0.2) maps.erl:416: :maps.fold_1/4
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:218: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

**Comment by SteffenDE** [comment] 2024-01-13 15:27
Duplicate of https://github.com/phoenixframework/phoenix_live_view/issues/2729, should be fixed on main.

**Comment by josevalim** [comment] 2024-01-13 15:34
Thank you @SteffenDE!

**Closed by josevalim** 2024-01-13 15:34 UTC
