### ISSUE TITLE
Uploader errors not showing for any subsequent files after the initial one

### ISSUE THREAD

**Issue by rohan-b99** [phoenixframework/phoenix_live_view#2664] opened 2023-06-05 09:48 UTC
### Environment

* Elixir version (elixir -v): 1.14.2
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): 0.19
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior:

Uploading a file initially correctly shows an error, but any subsequent files do not show errors - for example, try:
1. Upload a file
2. Upload another file - no error shown
3. Remove the initial file with the error - still no error shown

Reproduction here, adapted from https://github.com/mcrumm/live_upload_example/ - using the "ImmediatelyError" uploader to simulate errors:
[Single file app](https://gist.github.com/rohan-b99/8f8177bdb8a4d08b938c6b26d50abfbd)

### Expected behavior
The errors should show for each file

**Comment by josevalim** [comment] 2023-06-05 10:37
I have done an initial exploration and the issue may be coming from JavaScript. The UploadConf only holds a single error and the server callback that is invoked to add the errors is only invoked once (the first time, for the first error).

**Comment by CoderDennis** [comment] 2023-06-13 12:59
I found that part of the problem is in `Phoenix.LiveView.Channel`, the function clause `handle_info(%Message{topic: topic, event: "progress"} = msg, %{topic: topic} = state)` gets a `nil` in `msg.payload.ref` that causes the view to crash when calling `Upload.get_upload_by_ref!`.

When selecting more than one file at once that all have errors, only one of them produces a progress message with a ref that's not nil.

**Comment by dankentfield** [comment] 2023-08-02 09:18
@chrismccord @josevalim would it be okay if we take a look to fix this and open a pull request?

**Comment by CoderDennis** [comment] 2023-08-02 09:44
@dankentfield I realize you didn’t ask me, but I spent a little time investigating this issue and am not currently working on it.

**Comment by chrismccord** [comment] 2023-08-02 14:51
@dankentfield please do!

**Comment by chrismccord** [comment] 2023-09-19 20:28
Fixed on main. Going out via 0.19.6 shortly. Thanks!

**Closed by chrismccord** 2023-09-19 20:28 UTC
