### ISSUE TITLE
Intersperse adds extra whitespaces

### ISSUE THREAD

**Issue by MMore** [phoenixframework/phoenix_live_view#2602] opened 2023-04-25 03:53 UTC
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): 0.18.18
* Operating system: MacOS
* Tailwindcss
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari (both latest)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

The new `intersperse` component from #2243 is cool, but it adds extra whitespaces that I cannot get rid of. 😢 

```heex
~H"""
<div id="intersperse">
  <.intersperse :let={item} enum={["One", "Two"]}>
    <:separator>,</:separator>
    <%= item %>
  </.intersperse>
</div>
"""
```

Generated HTML:
![Screenshot 2023-04-24 at 20 42 30](https://user-images.githubusercontent.com/172760/234170503-791b67d8-d6c2-4986-9b7c-58702a4baa4d.png)

The _visible_ output is: `One , Two`.

### Expected behavior

The _visible_ output should be `One, Two`.

### Tries

- I tried using `phx-no-format` in the div around
- I tried with a `span` around `,` and `class="inline-block"`
- `class="inline-block"` in span around the item
- added a css class with pseudo class `sep:after { content: ",";}`
- I even removed the whitespaces in https://github.com/phoenixframework/phoenix_live_view/blob/e67b0e9429e904477a84b6face22dc5da53672c8/lib/phoenix_component.ex#L2382-L2392 and although I could eliminate some, it didn't help visually. It seems the `for` is adding something somewhere with these slots.

**Comment by aiwaiwa** [comment] 2023-04-26 20:11
`<option>` inside `~H` also adds new lines and empty new lines

```html
        <datalist id="europe-countries">
          <option>Germany</option>
          
          <option>United Kingdom</option>
          
          <option>France</option>
          
          <option>Italy</option>
```

**Comment by MMore** [comment] 2023-04-27 03:39
So how do you use `text-[0]` attribute specifically? @aiwaiwa

**Comment by aiwaiwa** [comment] 2023-04-27 10:01
@MMore MDN shows a great example:
https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace#example_3

Adding spaces between opening and closing tags can change the line-height and therefore affect the vertical spacing between elements. This can lead to unintended layout changes and cause compatibility issues across different web browsers.

**Comment by MMore** [comment] 2023-04-27 15:48
Couldn't find specifically for `text-[0]` there. Anyway, so the mentioned approaches there I basically tried already and don't work. Maybe somebody else finds something. Or we can fix it at the source.

**Comment by aiwaiwa** [comment] 2023-04-27 18:49
Sorry for confusion, `text-[0]` or `leading-[0]`, both useful in eliminating unnecessary white spacing, are essentially Tailwind custom classes, essentially generating `font-size: 0;` `line-height: 0;` on-the-fly.

**Comment by aiwaiwa** [comment] 2023-04-28 12:40
I just realized that I completely misunderstood the whole issue. (Typical dyslexic me!) Ignore my formatting comments please!

Back to the actual topic. I can confirm that on my end the final HTML also looks like this:

```html
<div id="intersperse">
  
  
    
    One
  
  

  
    ,
  

  
    
    Two
  
  

</div>
```

I use Edit as HTML when right clicking the item in Firefox to observe the underlying HTML.

**Comment by aiwaiwa** [comment] 2023-04-28 12:55
I don't think the expectation is that there's zero whitespace in HTML output, since you could simply render `Enum.intersperce` inline, if you really wanted to tighten the string and eliminate space around commas.

**Closed** 2023-05-12 20:24 UTC

**Comment by MMore** [comment] 2023-05-13 08:16
@chrismccord Thanks for your support! Unfortunately that change is not enough. I tried that already locally. As you can also see in the belonging test of your change, there is still a `\n` before and after the separator which leads to the visible whitespace.

**Comment by chrismccord** [comment] 2023-05-13 10:56
I don’t think the current whitespace is an issue. Is it causing display problems for you?

**Comment by MMore** [comment] 2023-05-13 18:07
Yes it does, as described above with a comma. The visible output is `One , Two` then.

**Comment by MMore** [comment] 2023-05-13 18:08
> I don’t think the current whitespace is an issue. Is it causing display problems for you?

@chrismccord Yes it does, as described above with a comma. The visible output is One , Two then.

**Comment by josevalim** [comment] 2023-05-13 19:03
In this case, isn’t it better to change the CSS rule for white space? Otherwise this is very fragile. Even if we change Phoenix to support it, you are a formatter command or a function component away of adding the spaces back.

**Comment by MMore** [comment] 2023-05-13 19:08
> In this case, isn’t it better to change the CSS rule for white space? Otherwise this is very fragile. Even if we change Phoenix to support it, you are a formatter command or a function component away of adding the spaces back.

@josevalim What do you mean with changing the CSS rule for white space? Above I stated what I tried to make it work. Maybe the `intersperse` component is just not meant for this use case?

**Comment by josevalim** [comment] 2023-05-13 19:33
This one: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

**Comment by MMore** [comment] 2023-05-13 19:42
> This one: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

@josevalim I see. Yes I played with that (using tailwind). It can collapse whitespaces (means making one of many whitespaces) but not fully remove them unless it's at the end of the line. :-(

**Comment by aiwaiwa** [comment] 2023-05-13 19:46
I know Go had to introduce a `{{-` and `-}}` syntax to their template language to trim any white space right before and right after it, due to some legit use cases when white space in TEXT or HTML output would create an issue.
https://pkg.go.dev/text/template#hdr-Text_and_spaces

**Comment by chrismccord** [comment] 2023-05-13 20:04
Also, since it doesn’t seem like you want to actually intersperse the commas with markup, then you can simply use enum intersperse
