### ISSUE TITLE
inputs_for/3 broken in 0.17.7

### ISSUE THREAD

**Issue by tfwright** [phoenixframework/phoenix_live_view#1935] opened 2022-03-26 19:44 UTC
### Environment

* Elixir version (elixir -v): Elixir 1.11.4 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.7
* Operating system: OSX
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox 98.0.1
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

Got an error that LiveView was unable to render a live component I added to a previously working form because it was inside inputs_for/4 function arg. Seeing that Phoenix.HTML.Form had inputs_for/3 specifically for compatibility with Live View, I switched to that.

### Actual behavior

 Immediately the view that had been rendering fine before that change hung indefinitely during rendering. Adding logs, I was able to see it seemed to stick after rendering the last field on the embedded form generated with inputs_for/3.

### Expected behavior

Form renders normally.

Downgrading to Phoenix Live View 0.17.5 immediately fixed the issue.

**Comment by josevalim** [comment] 2022-03-26 19:59
Can you please provide a small view or sample app that reproduces the problem? However, I don't think inputs_for/3 will work with HEEx anyway, so it should likely be removed/phased out in favor of inputs_for/4 or a long term replacement.

**Comment by josevalim** [comment] 2022-03-26 20:00
Ignore me. There are no closing tags on inputs_for, so it should be fine with HEEx. :)

**Comment by tfwright** [comment] 2022-03-26 20:34
Unfortunately it seems there are multiple converging factors behind the issue. The problem originated in [this library commit ](https://github.com/tfwright/live_admin/commit/4b3c51f82c7c83e46f2363c4014750f2eba4c060) (main branch) when used as a dep in another app. Note the library source at that ref locks to 17.5 and the use case works fine in the demo app there (which is why I tried the downgrade). The app was affected when locked to 17.7, and adding `{:phoenix_live_view, "~> 0.17.5", override: true}` solved the issue. 

I tried upgrading to 17.7 in the library but the use case still didn't break there. Furthermore, using [this version](https://github.com/tfwright/live_admin/commit/e5b4a5fc940b6c7b5629a1a18d5178396f97b100) of the library locked to the updated version in the app also locked to 17.7 _also_ solved the issue.

So, essentially this is now a non-issue for me since I have only observed it to affect usage in apps locked to 17.7, when the lib is locked to 17.5. Since updating both solves the issue, I don't think it's worth further investigating, but I can share the incompatible lock files if that would be helpful to you.

**Comment by josevalim** [comment] 2022-03-26 20:38
The issue is rather that the added new values to the wire protocol, which causes breakage. So bumping to latest LiveView and enforcing that on your users is the way to go. We had the same issue with the dashboard and it is not related to inputs for. Just lists in general.

**Closed by josevalim** 2022-03-26 20:38 UTC
