### ISSUE TITLE
Using the JS API to set values on input elements doesn't behave as expected

### ISSUE THREAD

**Issue by mfeckie** [phoenixframework/phoenix_live_view#1895] opened 2022-02-21 10:07 UTC
### Environment

* Elixir version (elixir -v): 1.13.2
* Phoenix version (mix deps): 1.6.0
* Phoenix LiveView version (mix deps): 0.17.7
* Operating system: OSX
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

This relates to a discussion on Slack https://elixir-lang.slack.com/archives/CD594E0UU/p1645435042526819

Example of trying to set value of a hidden input on a form in LiveView

```
 <button
      type="button"
      phx-click={
        JS.set_attribute({"value", "value-1"}, to: "##{input_id(f, :user_id)}")
        |> JS.dispatch("input", to: "##{input_id(f, :user_id)}")
      }
    >
      one
    </button>
    <button
      type="button"
      phx-click={
        JS.set_attribute({"value", "value-2"}, to: "##{input_id(f, :user_id)}")
        |> JS.dispatch("change", to: "##{input_id(f, :user_id)}")
      }
    >
      two
    </button>
    <%= hidden_input(f, :user_id) %>
```

(I know this code isn't beautiful, but was just to demonstrate the issue in a reproducible way)

This correctly sets the value on first click (`<input id="user_invite_form_user_id" name="user_invite_form[user_id]" type="hidden" value="value-1">`), but on the second click the payload sent over websocket doesn't change and the value in the DOM doesn't get updated.

The payload sent looks like this

```
["4","6","lv:phx-FtXChz-jFUmVxwLn","event",{"type":"form","event":"validate","value":"_csrf_token=DS8iARokAw1TMnRZagQtJw4ELSUeTyQ6yJFpWimbaPFnY1GAMOERQ5Ee&user_invite_form%5Bemail%5D=&user_invite_form%5Bname%5D=&user_invite_form%5Buser_id%5D=value-1&_target=user_invite_form%5Buser_id%5D","uploads":{}}]
```

### Expected behavior

I would have expected that the new value would get sent regardless.

Switching to a hooks based approach does work.

```ts
Hooks.Select = {
  mounted() {
    const target = this.el.getAttribute("phx-target");
    const value = this.el.getAttribute("phx-value");
    this.el.addEventListener("click", () => {
      const inputElement = document.getElementById(target) as HTMLInputElement;
      inputElement.value = value;
      inputElement.dispatchEvent(new Event("input", { bubbles: true }));
    });
  },
};
```

It would be great if we could add the ability to set a `value` using the JS API, or update documentation to let folks know that `set_attribute` will not work for this use case.

I'm happy to help with a PR if work is required 😄

**Comment by josevalim** [comment] 2022-02-21 10:40
Duplicate of #1873 and #1868. :)

**Closed by josevalim** 2022-02-21 10:40 UTC
