### ISSUE TITLE
Stream is not reset in handle_params on patch

### ISSUE THREAD

**Issue by nmk** [phoenixframework/phoenix_live_view#2629] opened 2023-05-15 13:33 UTC
### Environment

* Elixir version (elixir -v): 1.14.4
* Phoenix version (mix deps): main
* Phoenix LiveView version (mix deps): main
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): n/a
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: n/a

### Actual behavior

Using `stream(.., reset: true)` in handle_params when using `patch` does not reset the stream.

### Expected behavior

The stream should be reset.

I have added a test to demonstrate this: https://github.com/phoenixframework/phoenix_live_view/compare/main...nmk:phoenix_live_view:stream-reset-on-patch

Is this a problem with the test or my usage of `stream(..., reset: true)`?

**Comment by chrismccord** [comment] 2023-05-29 19:13
Fixed on main. Thanks!

**Comment by chrismccord** [comment] 2023-05-29 19:31
https://github.com/phoenixframework/phoenix_live_view/commit/4938b556b5acdd6bafa8b229fc786001642eeacc

**Comment by chrismccord** [comment] 2023-05-29 19:32
I see this is on the elixir test client. There was a similar bug on the js client that was fixed :)

**Comment by nmk** [comment] 2023-05-29 21:08
I *think* the reason for this not working in the elixir client is this line: https://github.com/phoenixframework/phoenix_live_view/blob/main/lib/phoenix_live_view/test/dom.ex#L385

The `data-phx-stream` attribute is only added on the JS side, so `stream_ref in stream_resets` always returns `false` when using LiveViewTest.

**Comment by chrismccord** [comment] 2023-05-30 13:49
@a3kov just so we are on the same page, are you seeing this in the browser or the elixir test client?

**Comment by chrismccord** [comment] 2023-05-30 13:54
@a3kov please open a new issue with the best details you can provide as well as your example markup/code. Thanks!

**Closed** 2023-06-02 00:32 UTC

**Comment by coladarci** [comment] 2023-09-08 16:01
I came cross this thread - I'm on `0.19.5` and was losing my mind on this issue; it appeared like things weren't working at all but it was because they were be shoved to the end of the stream. Adding `reset: true` isn't wiping out the previous tiles on the page inside a patch. I'm in safari..

Template:
```
<div phx-update="stream">
              <Components.tile
                :for={{_id, tile} <- @streams.tiles}
                tile={tile}
              />
</div>
```

Code: 
```
def handle_params(params, _uri, socket) do
  {:noreply, stream(socket, :tiles, get_tiles(params) reset: true)}
end
```

**Comment by nmk** [comment] 2023-09-11 07:04
@coladarci The problem I described here only affects the elixir test client. If you are having a problem in the browser, I would suggest opening a separate issue.

If I have understood the code correctly, the Elixir test client has to emulate quite a lot of what the JS part of LiveView does. It is inevitable that the two implementations would drift apart sometimes. That is why in this case we have failing tests for code which works as intended in the browser.

**Comment by coladarci** [comment] 2023-09-12 23:41
THANK YOU @nmk this gave me the confidence in the lack of confidence in my code. It was the lack of using the stream's id on the dom element that was causing them to stick around...

**Comment by nathanalderson** [comment] 2023-09-22 17:05
I'm still seeing issues with this on 0.19.5 in tests. Works fine in the browser, but when I use `stream(..., reset: true)` then the test client isn't removing old items from the stream. I'm not doing any patching or navigating, just calling the stream reset from a `handle_event`. Items all include the `dom_id` from the stream item and I include `phx-update="stream"` on the parent element.

**Comment by nathanalderson** [comment] 2023-09-22 18:51
I was able to reproduce my issue in the testbench. I opened a new issue: #2816.
