### ISSUE TITLE
Object sent to client contains unchanged stream item data

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#2842] opened 2023-10-03 14:20 UTC
### Actual behavior

When not using my own (server-side) diffing mechanism but choosing to rely entirely on the LV streams instead, on each stream update the object sent to the client has two lists each containing some basic data for each of the items provided to the stream (via `stream/4` or `stream_insert/4`) even for the unchanged items, e.g.:

```javascript
{
"0": {
  "5": {
    "0": 3
  }
},
"c": {
  "3": {
    "7": {
      "d": [
        [
          {
            "0": {
              "0": {
                "0": 4,
                "s": 0
              },
              "s": 1
            },
            "s": 2
          }
        ],
        [
          {
            "0": {
              "0": {
                "0": 5,
                "s": 0
              },
              "s": 1
            },
            "s": 2
          }
        ],
  ...

"stream": [
  "3-0",
  {
    "Entry-21cbae0a-1c30-436f-bc82-999ecb8b3a82": [
      -1,
      null
    ],
    "Entry-5f64b5f3-ec88-42e9-bd5f-b92499a2e1d9": [
      -1,
      null
    ],
    "Entry-65e45f65-51eb-4d76-8c9f-8960b6972644": [
      -1,
      null
    ],
  ...
```

This is particularly observable in the use case where LV acts as an HTTP client based frontend fetching paginated lists with pages of say 10 or 20 items (depending on the backend config) as the minimal units, even on updates i.e. on cache invalidation events.

### Desired behavior

LiveView should only send the items that actually changed, or at least support an option instructing it to do so.

**Comment by josevalim** [comment] 2023-10-03 14:23
Can you please include the LV version? Also, can you please mention how you are accessing this payload? Are you looking at the Websocket messages directly?

**Comment by josevalim** [comment] 2023-10-03 14:34
Try checking out the websocket instead. The  data in the browser is mutable and may include merged data. If the issue persists, please provide a small app to reproduce it. :)

**Comment by DaTrader** [comment] 2023-10-03 14:35
Ok

**Comment by chrismccord** [comment] 2023-10-03 14:47
Any stream insert you do will be sent to the client. There is no way for the server to know if the stream item did or did not change because we don't keep a copy of it (by design). If you want diffed items, you could look into LiveComponents, but the behavior is correct – any item you insert into a stream is sent to the client. Thanks!

**Closed by chrismccord** 2023-10-03 14:47 UTC

**Comment by josevalim** [comment] 2023-10-03 14:54
Oh, it is sending the same items every time? Then yes, it will be sent every time. :)

**Comment by DaTrader** [comment] 2023-10-03 15:25
@chrismccord Those items ARE LiveComponents and I am not referring to the changes within them - those are not being sent every time, only for those that actually changed. However, those two lists are sent every single time even if the items (components) are unchanged. And it's not like you can't tell which ones didn't change - you use hash for that.

**Comment by DaTrader** [comment] 2023-10-03 15:49
@chrismccord I am asking you to reconsider this design decision. There's no reason why the unchanged items should be sent over the wire and yes, you can use the hash you're already using to tell if they changed. Doing so the streams would become complete in terms of diffing.

**Comment by chrismccord** [comment] 2023-10-03 16:48
You need to share code for us to say with certainty, but if you do `stream(socket, :items, items)` and expect only the items that changed to be sent, that will never be the case – we don't track the items by design.

**Comment by DaTrader** [comment] 2023-10-03 18:03
Yes, that's exactly what I would like to do in order to replace my own diffing mechanism in favor of having the streams do all the job instead. TBH, when I first read the streams docs, I even assumed it was the case (the hope prevailed :).

Also, I can't figure out why you are so determined it's a good idea not to track them, specially given that you are already tracking them individually if they are LiveComponents - so all it takes is adding the code to drop any mention of them from the object stream data as well when unchanged (from the two lists as shown in the snippet). 

Lots of people may have this case fetching many and expecting to update only the ones that changed. This is precisely the kind of issue I used to have with the LV lists prior to the introduction of streams. Please keep in mind that people building only the frontend don't have much choice then. Either letting all the items get sent each time or diffing them themselves server side (like I've been doing since the LV lists).

**Comment by josevalim** [comment] 2023-10-03 18:53
The goal of streams is to have as little footprint on the server as possible. Tracking sent IDs or hashes would directly go against that. You can do your own tracking though, which you seem to be already familiar with. :)
