### ISSUE TITLE
Select field with focus not updated

### ISSUE THREAD

**Issue by DragosMocrii** [phoenixframework/phoenix_live_view#1313] opened 2021-01-12 20:10 UTC
### Environment

* Elixir version (elixir -v): 1.11.2
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.3
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome

### Actual behavior

I have a form that validates itself when phx-change is triggered, but errors are not being displayed unless I submit the form, at which point the changeset gets an action applied so the errors are being displayed. The form contains a select field that gets the `is-invalid` class if the select field is blank/unselected. If I submit the form when the select field is blank, the field will get the `is-invalid` class. Now, if I choose a value for the select, the `phx-change` event is triggered, the form is  re-rendered, and the field loses the `is-invalid` class (I can see it in the returned diff). However, on the front-end the select field still keeps the `is-invalid` class. I believe this is because Phoenix LiveView does not update fields that are in focus. Now, if I submit the form right after I previously selected a value in the select, the `is-invalid` class is still there, because there is no diff returned at this time, so nothing for LiveView to update on the front-end. If I make a change on another field, then LiveView tracks the changeset changes, and re-renders the form, and the select field is properly displayed without the `is-invalid` class. I haven't tried it yet, but I think if I write code to make the select field lose the focus after the value changes, this should make LiveView patch the field with the changes. Obviously, this is not a good UX since someone using a keyboard to navigate the form, will be frustrated.

### Expected behavior

The select field should be updated when the value changes, regardless if it has focus or not (since a select field is not like a text field where we are concerned about the value).

**Comment by chrismccord** [comment] 2021-01-12 20:14
Can you put together a minimal LV/template that reproduces this? Thanks!

**Comment by DragosMocrii** [comment] 2021-01-12 21:05
Tried to set up a new Phoenix LV project, but I am running into a dependency hell on my machine, so unfortunately I'll need to postpone this for a later time.

I did however test my theory, and added an event listener that blurs the select field right after its value changes. With this, Phoenix LiveView patches the DOM correctly. Without it, the patch for the focused select is lost.

**Comment by gnegno84** [comment] 2021-01-13 09:50
Hi, I'm having a similar issue.
I've created a public repo with a minimal project to reproduce it. 
I'm actually working on a project that uses Surface, so the repo was focused first on reproducing the issue using Surface.
Then I've added a LiveView only page to better point out the source of the issue. (route: http://localhost:4000/lv-test)

The repo is available here:
[https://github.com/gnegno84/surface_test](https://github.com/gnegno84/surface_test)

**Comment by daveli** [comment] 2021-02-03 11:42
@DragosMocrii I tried your suggestion with applying blur to make it work but it seems to have no effect. Could you provide some example code? :)

**Comment by daveli** [comment] 2021-02-03 14:54
This seems to be fixed in 0.15.4 see: https://github.com/phoenixframework/phoenix_live_view/commit/9b2a0b8a21f56b1dcbadeb54b1eba0c492a5aa2d

**Closed** 2021-02-03 15:44 UTC

**Comment by feliperenan** [comment] 2022-05-18 16:46
@james-the-elixir-guy can you tell if you are facing this issue using Live View master?

**Comment by mcrumm** [comment] 2022-05-18 18:56
Hi @peaceful-james– I think what @feliperenan meant was have you tried using the latest commit on the `master` branch of this repo :)

That said, this is currently the expected behaviour. As we mention in the [JavaScript client specifics](https://hexdocs.pm/phoenix_live_view/form-bindings.html#javascript-client-specifics) section of the Form bindings guide on Hexdocs, the client is always the source of truth for form inputs, so we don't update form values when the input has focus. In the case of a focused `<select>` we don't update the input at all. There are several reasons for this, one being a bug in Firefox. See #627 and #1525. Thanks!

**Comment by josevalim** [comment] 2022-05-19 05:31
I believe if you change the id of the select element, it will reload it. So for example, if you are generating different options based on other inputs, you can change the id to force a whole new select.

**Comment by peaceful-james** [comment] 2022-05-19 06:14
> I believe if you change the id of the select element, it will reload it.

Yes! https://github.com/peaceful-james/live-view-focused-select-bug/tree/try-changing-id-a-la-jose

When I add a dynamic ID, like this:

```
id: "#{if Keyword.get(f.errors, :color), do: "select-color-error", else: "select-color-ok"}",
```

then the element is reloaded, along with the dynamic class.

There is one unfortunate side effect - a keyboard-only user will lose focus on the `<select>` element when the ID changes.

**Comment by koxu1996** [comment] 2022-08-30 11:08
I am also experiencing this issue :disappointed: Workaround with dynamic ID works for now.

**Comment by objectuser** [comment] 2023-03-24 16:03
Same issue. I don't see an actual fix though the issue is closed.
