### ISSUE TITLE
Stream consumed/rendered twice is not rendered in tests (but app works fine)

### ISSUE THREAD

**Issue by shamanime** [phoenixframework/phoenix_live_view#3098] opened 2024-02-07 20:57 UTC
### Environment

* Elixir version (elixir -v): Elixir 1.16.0 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): 1.7.11
* Phoenix LiveView version (mix deps): 0.20.4
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari, FF
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Issue

I have the following scenario:

1. LiveView initializes an empty stream and fires an async task using start_async.
2. handle_async then updates the stream when data is fetched.
3. Stream is consumed twice on the template (once to display the list of records, and one more time to display a list of dialogs related to the record)
4. The app works fine. The list and dialogs are rendered.
5. When testing it is possible to assert on the list rendered, but asserting on the dialogs (where the stream is consumed/rendered the second time) fails. Using open_browser and inspecting confirms the issue, the desired content is missing. 

With LV 0.20.3 test passes. With 0.20.3 and 0.20.4 using the app works fine. Issue is with the test only.
With main up to https://github.com/phoenixframework/phoenix_live_view/commit/4b8d63aabf3f6b62e76bc358a67d09487f58e57a the test also fails.

I have created an repo with a failing test related to the issue and this is the relevant changes to reproduce the bug:
https://github.com/shamanime/async_stream_test/commit/409b034348329d52ab0d45d52396f1cfccb438e3

[Here](https://github.com/shamanime/async_stream_test/blob/main/lib/lv_async_stream_test_web/live/user_live/index.html.heex#L48) is the second time the template iterates over the stream. And [this](https://github.com/shamanime/async_stream_test/blob/main/test/lv_async_stream_test_web/live/user_live_test.exs#L31) is the failing assertion.

**Comment by SteffenDE** [comment] 2024-02-07 22:24
Related to https://github.com/phoenixframework/phoenix_live_view/pull/3078.

This is caused by the stream being rendered two times in the same LiveView, the second time with ids that are not the same as the `dom_id` value of the stream item. This leads to LiveViewTest not finding the child. Previously (in 0.20.3 and earlier) we ignored such children, keeping them in the tree, but after the changes to properly limit stream items in https://github.com/phoenixframework/phoenix_live_view/pull/3035 the code was changed in a way that non stream items are not included.
Using non stream children inside a stream container brings other problems as well, so while the items are rendered in the browser, for example stream updates will not work as expected.

**Comment by SteffenDE** [comment] 2024-02-07 22:44
@shamanime you should be fine by just using two different streams with the same items and then always doing the operations on both streams, for example

```
socket
|> stream_insert(:users, user)
|> stream_insert(:delete_users, user)
|> then(&{:noreply, &1})
```

**Comment by josevalim** [comment] 2024-02-08 06:44
Closing in favor of the PR and the feedback above. :)

**Closed by josevalim** 2024-02-08 06:44 UTC
