### ISSUE TITLE
Statefull LiveComponent does not honor :temporary_assigns

### ISSUE THREAD

**Issue by clemensm** [phoenixframework/phoenix_live_view#1180] opened 2020-10-08 12:13 UTC
### Environment

* Elixir version: 1.10.4
* Phoenix version: 1.5.3
* Phoenix LiveView version: 0.14.7
* Operating system: macOs
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome

### Actual behavior

Statefull LiveComponent does not reset temporary assigns on next render. 

I.e. I've got a LiveView with a statefull LiveComponent. The LiveComponent has an assing called `:too_short`, which is a boolean value. I return the following from the `mount` callback in the LiveComponent:

```
{:ok, assign(socket, too_short: false), temporary_assigns: [too_short: false]}
```

If I then set the `:too_short` assign in a handler, like so:

```
{:noreply, assign(socket, too_short: true)}
```

it will not be reset on subsequent events and rerenders.

### Expected behavior

Statefull LiveComponent should reset temporary assigns on render to provided default value.

**Comment by josevalim** [comment] 2020-10-08 13:02
Can you please provide a sample application that reproduces the error? I have just tried it locally in one of my apps and it worked fine. We also have tests that show this behaviour is working as intended. Thanks.

**Comment by josevalim** [comment] 2020-10-09 10:14
Closing for now, please include a mechanism to reproduce the issue and we will gladly reopen!

**Comment by clemensm** [comment] 2020-10-10 11:42
So I've found some time to create an example app, see attachment. It's basically just a simple LiveView (called `EditorView`) that contains a single statefull LiveComponent (`SearchItems`). Inside the component there's a text input, and an assign `term_too_short` that should be reset to `false` after each render. `term_too_short` triggers an error message below the input field that you need to type at least 3 chars.

So to trigger the bug:

1. Open the site. In the input, enter just one char.
2. An error message is shown below the input.
3. Enter more then 3 chars.
4. Expected result: The error message is removed.

Thanks and have a nice weekend :-) 

[bug.zip](https://github.com/phoenixframework/phoenix_live_view/files/5358916/bug.zip)

**Comment by josevalim** [comment] 2020-10-10 18:39
So this is the same

**Comment by josevalim** [comment] 2020-10-10 18:42
So this is the same issue as I have been discussing with as #1169. Temporary assigns should not be used to "control state" because once a temporary assign is set, it is never re-rendered again. Do not use temporary assigns here, instead, set it to true/false and in the if/else branches accordingly. I will add a note to the docs. Thanks!

**Closed by josevalim** 2020-10-10 18:42 UTC
