### ISSUE TITLE
Upgrading to 0.20.4 breaks something

### ISSUE THREAD

**Issue by atomkirk** [phoenixframework/phoenix_live_view#3095] opened 2024-02-06 23:52 UTC
All I did is bump from 0.20.3 -> 0.20.4 and now I'm getting this console error:

<img width="602" alt="CleanShot 2024-02-06 at 16 51 00@2x" src="https://github.com/phoenixframework/phoenix_live_view/assets/2091439/237e2f6a-4e37-42a3-b382-9277c6975b90">

when I pin back to 0.20.3 its fixed again.

It breaks when trying to use multiple components from the petal framework. Sorry I don't have more information but I figured at bug fix bump would be safe.

**Comment by SteffenDE** [comment] 2024-02-07 00:08
This is a known issue, sorry about that. A fix will be available in the next release.

Duplicate of #3087. Already fixed on main.

In the meantime you can pin LiveView to a known good version from git:

`{:phoenix_live_view, github: "phoenixframework/phoenix_live_view", tag: "a222c7fb8cb459089b13250a42c069b6d34a71ad", override: true}`

or just stay with `{:phoenix_live_view, "0.20.3"}` for now.

**Closed** 2024-02-07 13:59 UTC
