### ISSUE TITLE
Chrome doesn't scroll to anchor when the page has an embedded liveview

### ISSUE THREAD

**Issue by skovmand** [phoenixframework/phoenix_live_view#1204] opened 2020-11-05 11:07 UTC
### Environment

* Elixir version (elixir -v): 1.11.1
* Phoenix version (mix deps): 1.5.6
* Phoenix LiveView version (mix deps): 0.14.8
* NodeJS version (node -v): v12.19.0
* NPM version (npm -v): 6.14.8
* Operating system: Windows 10, Fedora 32
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome 86, Firefox 82
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Thank you for the great work on `live_view` :+1: .. 

I have an issue with Chrome 86 that doesn't scroll to anchor elements when a liveview is embedded in the page.

When I navigate from one page to another when the destination contains a location hash, e.g. `http://localhost:4000/page2#comments`, Chrome does not scroll to the element with the location hash id. The navigation in question is a regular navigation/link, not a LiveView redirect or patch. When Chrome renders the destination page, the page is displayed from the top (at scrollposition 0px), but it should have scrolled to the `id` specified in the location hash.

I have found that this happens when a live view is embedded in the destination page.

It is reproduced in https://github.com/skovmand/live_view_anchor_bug

### Expected behavior

The expected behaviour is that Chrome scrolls to the location hash automatically when the destination page is loaded.

**Comment by josevalim** [comment] 2020-11-05 11:59
Quick question: does this behavior happen in other browsers? Also, can you please quickly try LiveView master? Thank you.

**Comment by skovmand** [comment] 2020-11-05 12:16
- Does it happen in other browsers?

Firefox 82.0.2 doesn't have the bug. It scrolls correctly all the time.
Chrome 86 has the bug on both Fedora 32 and Windows 10
I haven't got other browsers available unfortunately.

- Does it happen on latest `live_view` master:

I added the dependency to `mix.exs`:

```
{:phoenix_live_view, git: "https://github.com/phoenixframework/phoenix_live_view.git", branch: "master"}`
```

and ran `mix deps.get` to get the latest master commit. I had to remove all live dashboard functionality because of a conflict I didn't dive in to. I then removed `assets/node_modules` and ran `npm ci` from the `assets` dir.

I can confirm that the problem persists on newest master: It works as intended in Firefox, but not in Chrome.

**Comment by skovmand** [comment] 2020-11-05 12:17
I have added the code changes I made to the `latest_master` branch: https://github.com/skovmand/live_view_anchor_bug/tree/latest_master

**Comment by cw789** [comment] 2020-12-15 08:24
This Issue is related to: https://github.com/phoenixframework/phoenix_live_view/pull/1256
It started with PR: https://github.com/phoenixframework/phoenix_live_view/pull/1123

**Comment by winescout** [comment] 2021-02-14 00:23
I did something similar to @skovmand , so I'll post it here as well.  https://github.com/winescout/live_view_anchor_tags.

I can confirm that the issue is present in Safari and Mobile Safari

Per Jose's suggestion above, I'll give it a go against the current master.

**Comment by winescout** [comment] 2021-02-14 00:34
Master has the expected behavior.  in Chrome and IOS new.  Thanks!

**Comment by skovmand** [comment] 2021-02-14 18:24
Nice! Did you verify that the bug was fixed in `master`?

**Comment by winescout** [comment] 2021-02-15 21:18
Yep.  I was fixed in Master, and 0.15.4 I believe

**Comment by skovmand** [comment] 2021-02-16 11:17
Nice! I will just check it on my machine too today

**Comment by skovmand** [comment] 2021-02-16 14:39
It is fixed on my machine as well. Nice!

**Closed** 2021-02-16 14:41 UTC
