### ISSUE TITLE
No component for CID bug

### ISSUE THREAD

**Issue by sezaru** [phoenixframework/phoenix_live_view#3059] opened 2024-01-27 00:09 UTC
### Environment

* Elixir version (elixir -v): 1.16.0
* Phoenix version (mix deps): 1.7.10
* Phoenix LiveView version (mix deps): 0.20.3
* Operating system: Fedora Silverblue 39
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox 121.0, Chrome 121.0.6167.85
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

In my application, I have a table that will reload data when the user click in the `Search` button. If the user clicks on it 2~3 times, I will get an `No component for CID` error in the browser console and the table will not load correctly.

Since I don't know exactly why this error is triggering, I created a small project that will trigger the issue, you can get it here: https://github.com/sezaru/liveview_cid_bug

I believe it is a race condition in the JS code or something like that because it is easier to trigger it if I add some sleep time during the load process (`lib/marketplace_web/live/admin/disposition/list_live.ex:47`).

The cid that it can't find is a cid of the `SkipTrace.Row` component (`lib/marketplace_web/components/admin/skip_trace/row.ex`).

So, again, to trigger the issue, you will need to run the example project above, then you can just click in the search, wait it to load, then click in search again and you will probably trigger it, here is a video showing how to trigger it:

![2024-01-26 20-59-08](https://github.com/phoenixframework/phoenix_live_view/assets/279828/62588239-de28-444b-8492-5a11f2239afd)

Also, I find it easier to trigger in Firefox, but I'm also able to trigger it in Chrome.

### Expected behavior

No javascript exception is triggered and load the table correctly.

**Comment by SteffenDE** [comment] 2024-01-27 04:24
Hi there, can you try `{:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main", override: true}` in your mix.exs and see if that fixes your issue? There are some unreleased bug fixes that could already address this.

**Comment by SteffenDE** [comment] 2024-01-27 11:38
Thank you for the reproduction. I can confirm that this is indeed fixed on main.

Duplicate of https://github.com/phoenixframework/phoenix_live_view/issues/2180, fixed via https://github.com/phoenixframework/phoenix_live_view/commit/20080a54303cf8110c040e99d6042dc7a4ff2621.

You can use `{:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main", override: true}` until the next release. Thanks!

**Closed by SteffenDE** 2024-01-27 11:38 UTC
