### ISSUE TITLE
Got the errors when call live_patch from stateful LiveComponents

### ISSUE THREAD

**Issue by leductam** [phoenixframework/phoenix_live_view#661] opened 2020-02-25 18:05 UTC
### Environment

* Elixir version (elixir -v): 1.10.1 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): 1.5.0-dev locked at ec06fb3
* Phoenix LiveView version (mix deps):  0.8.0 locked at 8cb3b4c
* NodeJS version (node -v): v13.9.0
* NPM version (npm -v): 6.13.7
* Operating system: Window 10 Pro Version 1903
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Got the errors when using live_patch to navigate/switch the tabs on the master page HomeLive. The error as below appeared when live_patch **from a table_tab** has the table with each row is the stateful LiveComponent **to a detail_tab** (doesn't have the table).

Uncaught TypeError: Cannot convert undefined or null to object
    at eval (phoenix_live_view.js:453)
    at Array.forEach (<anonymous>)
    at Object.pruneCIDs (phoenix_live_view.js:452)
    at eval (phoenix_live_view.js:1901)
    at Object.eval [as callback] (phoenix_live_view.js:1733)
    at eval (phoenix.js:229)
    at Array.forEach (<anonymous>)
    at e.value (phoenix.js:228)
    at Object.eval [as callback] (phoenix.js:247)
    at e.value (phoenix.js:406)

The messages:
        ["4","5","lv:phx-Ffa14jmqM4ATDgCm","link",{"url":"http://localhost/home?p=detail"}]
	["4","5","lv:phx-Ffa14jmqM4ATDgCm","phx_reply",{"response":{"diff":...
	["4","6","lv:phx-Ffa14jmqM4ATDgCm","cids_destroyed",{"cids":[0,1,2]}]
	["4","13","lv:phx-Ffa14jmqM4ATDgCm","phx_reply",{"response":{},"status":"ok"}]

After that, when back to the **table_tab** and changed the assigns, the **table_tab** is hang re-render and got the errors:

Uncaught TypeError: Cannot read property '0' of undefined
    at Object.toOutputBuffer (phoenix_live_view.js:436)
    at Object.toString (phoenix_live_view.js:431)
    at Object.componentToString (phoenix_live_view.js:416)
    at Object.dynamicToBuffer (phoenix_live_view.js:449)
    at Object.comprehensionToBuffer (phoenix_live_view.js:445)
    at Object.toOutputBuffer (phoenix_live_view.js:434)
    at Object.dynamicToBuffer (phoenix_live_view.js:449)
    at Object.toOutputBuffer (phoenix_live_view.js:438)
    at Object.toString (phoenix_live_view.js:431)
    at e.value (phoenix_live_view.js:1560)

The messages:
        ["4","29","lv:phx-Ffa14jmqM4ATDgCm","link",{"url":"http://localhost/home?p=table"}]	
	["4","29","lv:phx-Ffa14jmqM4ATDgCm","phx_reply",{"response":{"diff":{"0":{"0":....

Note: This issue is not happen after removing the id of table rows to change stateful to stateless LiveComponent.

### Expected behavior
Don't get the errors and can re-render the stateful LiveComponent.

**Comment by josevalim** [comment] 2020-02-25 18:08
Can you please provide an application that reproduces the error? Otherwise it may take us a lot of time to get to the end of this. Thank you!

**Comment by leductam** [comment] 2020-02-26 08:40
I've updated the naive application to reproduces the errors, please review.
https://github.com/leductam/live_view_patch

**Comment by chrismccord** [comment] 2020-02-26 14:54
Thanks for the reproduction! This only happened when a new fingerprint was sent to the client and would fail to initialize the component tracking, which was caused by this code in the example:
```
  def render(assigns) do
    View.render("#{assigns.tab}.html", assigns)
  end
```

**Comment by leductam** [comment] 2020-02-26 15:31
Thanks for your prompt response, but after update the js commit there are another error:
Uncaught TypeError: Cannot read property '0' of undefined
    at Object.toOutputBuffer (phoenix_live_view.js:434)
    at Object.toString (phoenix_live_view.js:409)
    at Object.recursiveCIDToString (phoenix_live_view.js:452)
    at Object.dynamicToBuffer (phoenix_live_view.js:447)
    at Object.comprehensionToBuffer (phoenix_live_view.js:443)
    at Object.toOutputBuffer (phoenix_live_view.js:432)
    at Object.dynamicToBuffer (phoenix_live_view.js:447)
    at Object.toOutputBuffer (phoenix_live_view.js:436)
    at Object.toString (phoenix_live_view.js:409)
    at e.value (phoenix_live_view.js:1569)

The reproduction:
Step 1: Open http://localhost/home; and perform multi click the labels "Region",  "Global".
Step 2: Click button "KPI" to switch tab
Step 3: Click button "SALES" to switch tab; and perform multi click the labels "Region",  "Global"; then hang re-render and got the JS errors.

**Comment by chrismccord** [comment] 2020-02-26 20:25
Closed by José via deda688a723fa22c2a1edc9bfe9c0b15964c0cc0

**Comment by chrismccord** [comment] 2020-02-26 20:26
Btw thank you @leductam for the repro example project and instructions. This was super helpful in tracking these two bugs down <3

**Closed by chrismccord** 2020-02-26 20:25 UTC
Labels: awaiting feedback

**Comment by leductam** [comment] 2020-02-26 21:11
I tested and the issue is fixed. I appreciate the prompt response and thanks Chris and José.
