### ISSUE TITLE
Phoenix.LiveViewTest.render_upload/3 crashes when upload process redirects

### ISSUE THREAD

**Issue by mogest** [phoenixframework/phoenix_live_view#2047] opened 2022-06-01 20:44 UTC
### Environment

* Elixir version (elixir -v): 1.13.3
* Phoenix version (mix deps): 1.6.7
* Phoenix LiveView version (mix deps): 0.17.9
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): n/a
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: n/a

### Actual behavior

Using `render_upload` when the upload function returns `{:noreply, push_redirect(socket, to: some_url)}` causes the following error:

```
     ** (FunctionClauseError) no function clause matching in Floki.RawHTML.build_raw_html/4

     The following arguments were given to Floki.RawHTML.build_raw_html/4:
     
         # 1
         [error: {:live_redirect, %{kind: :push, to: "/url"}}]
     
         # 2
         []
     
         # 3
         &HtmlEntities.encode/1
     
         # 4
         :noop
```

It's because this line in [Phoenix.LiveViewTest.render_chunk/3](https://github.com/phoenixframework/phoenix_live_view/blob/f862873ef0a4b72d2cfa21e538bef93c6f1abdcb/lib/phoenix_live_view/test/live_view_test.ex#L1743) calls `render/1` and that doesn't work with a redirect.

Makes sense—the function is called `render_upload` after all—but there's no way to to perform an upload otherwise as private functions are used.

### Expected behavior

I don't think we should change the functionality of `render_upload`, but I propose a new function `perform_upload` that does the same without rendering; instead it can return `:ok | {:error, atom()}`.

Then `render_upload` can be refactored to use the new `perform_upload` function and render the view in the `:ok` case.

I'm happy to code this up as a PR but wanted to check in that that was a sensible path to take first.

**Comment by mcrumm** [comment] 2022-06-01 22:09
Hi @mogest – I think this issue is a duplicate of #1620. Are you consuming the entry in the progress callback?

**Comment by chrismccord** [comment] 2024-01-19 18:38
Closed via eeafb2a5834645d812264a3032192639c4473777

**Closed by chrismccord** 2024-01-19 18:38 UTC

**Comment by cbh123** [comment] 2024-06-08 03:33
## Environment
- Elixir version (elixir -v): 1.16.2
- Phoenix version (mix deps): 1.7.11
- Phoenix LiveView version (mix deps): 1.0.0-rc.0
- Operating system: MacOS
- Browsers you attempted to reproduce this bug on (the more the merrier): n/a
- Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: n/a

## Actual behavior
Hmm, I'm still seeing this even after updating to :phoenix_live_view, "~> 1.0.0-rc.0" (with your commit). 

I'm running the same logic as @mogest where I redirect after uploading an image, and I get this error when I try and test it.

Test:
```elixir
      {:ok, view, _html} = live(conn, "/dashboard")

      assert render(view) =~ "free plan"

      # Upload an image file
      image = view |> file_input("#upload-form", :image, [image_fixture()])

      render_upload(image, image_fixture().name) 
```

Result:
```
     ** (FunctionClauseError) no function clause matching in Floki.RawHTML.build_raw_html/5

     The following arguments were given to Floki.RawHTML.build_raw_html/5:

         # 1
         [error: {:live_redirect, %{kind: :push, to: "/uploads/275a4e57-2503-40a1-b6f1-b5acee055383"}}]
```

I've tried `rm -rf _build` a couple times to make sure it's actually running the new code, and I've confirmed that my `channel.ex` uses the https://github.com/phoenixframework/phoenix_live_view/commit/eeafb2a5834645d812264a3032192639c4473777 commit from @chrismccord.

**Comment by PJUllrich** [comment] 2025-02-04 17:40
I've encountered the same issue today, so it's still unresolved unfortunately I think. cc @SteffenDE @chrismccord

**Comment by SteffenDE** [comment] 2025-02-04 17:41
@PJUllrich If you can find out how to reproduce, that would help a lot! Feel free to open up a new issue.

**Comment by PJUllrich** [comment] 2025-02-04 17:42
@SteffenDE thank you, will do. I also realized I'm still running LiveView 0.20.17. Will upgrade to the latest LiveView, try again, and open another issue if the bug still exists.
