### ISSUE TITLE
Phoenix.Component.used_input? does not work for changesets with Changeset.change/2 (as opposite to Changeset.cast/4)

### ISSUE THREAD

**Issue by Cervajz** [phoenixframework/phoenix_live_view#3337] opened 2024-07-09 12:09 UTC
### Environment

* Elixir version (elixir -v): 1.17.0-otp-27
* Phoenix version (mix deps): 1.7.14 (from the main branch)
* Phoenix LiveView version (mix deps): 1.0.0-rc.6
* Operating system: N/A
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

[Phoenix.Component.used_input? ](https://github.com/phoenixframework/phoenix_live_view/blob/2f82be7f78c7ab339798ff65cdf6076a73715315/lib/phoenix_component.ex#L1587) relies on **form.params** to determine if the field has been "touched" by the user or not. The **form.params** is populated from **changeset.params** via **to_form** protocol in https://github.com/phoenixframework/phoenix_ecto/blob/main/lib/phoenix_ecto/html.ex#L7 

However, this does not work when the data to the changeset were provided via Changeset.change/2 instead of Changeset.cast/4. The **changeset.params** map is empty for that route. 

The outcome is that no individual field errors are visible in the form as [the field is not evaluated as touched](https://github.com/phoenixframework/phoenix/blob/main/priv/templates/phx.gen.live/core_components.ex#L295). 

I created a simple application where the issue is reproduced, see https://github.com/Cervajz/lv_field_errors  

Once running, navigate to http://localhost:4000/links/new 

![CleanShot 2024-07-09 at 13 46 30](https://github.com/phoenixframework/phoenix_live_view/assets/344227/39c9bcaa-80bd-4e8b-91d4-9836bd95df47)

### Expected behavior

Display changeset errors for "touched" fields no matter the route the data entered the changeset.

![CleanShot 2024-07-09 at 13 47 14](https://github.com/phoenixframework/phoenix_live_view/assets/344227/02aa4716-247e-4ea4-99a9-e14ff881a019)

---

### Background

We like to keep our "core modules" (basically Phoenix Context) API explicit when working with resources. As those modules are not connected to the web layer in any way and could be used in non-web parts of the application, we don't like to send the form parameters (a raw map with binary keys) directly to the core functions (such as create, update or validate). We prefer those functions to have explicit set of arguments describing exactly what is necessary for creating/updating given resource (explicit API). 

For that reason we do perform basic validation and casting of the data before it enters the core API - in the web layer. This is demonstrated in the application I created for this issue

The above is heavily inspired by Saša Jurić's [Towards Maintainable Elixir: The Core and the Interface](https://medium.com/very-big-things/towards-maintainable-elixir-the-core-and-the-interface-c267f0da43), see the article for more details if interested. 

I understand that this is not the "Phoenix way". However, this issue is not about determining if it's the correct design of Core/Context modules or not. I believe the errors should be displayed independently of the way the data entered the changeset.

**Comment by SteffenDE** [comment] 2024-07-12 21:17
used_input relies on the `_unused_field` parameters sent to the LV being available in the form's `params`. So the problem is not really cast vs change, but rather that the information about the unused field is just not available if you don't have the params in the final form struct. And if you use `change`, there are simply no params.

You could either use the phx-feedback-for shim to keep the client-side feedback handling, or adjust your code in a rather minimal way to put the original params back into the form, for example like this:

```elixir
defp assign_form(socket, changeset, params) do 
  assign(socket, form: %{to_form(changeset, action: :validate, as: :link) | params: params})
end
```

(And then pass the link_params to `assign_form`)

**Comment by SteffenDE** [comment] 2024-07-27 10:55
I'll close this for now, as I'd say it works as intended. Let me know if you've got any more questions.

**Closed by SteffenDE** 2024-07-27 10:55 UTC

**Comment by shibaobun** [comment] 2025-07-23 02:32
I just ran into this behavior and with no indication for the need of params, I had to eventually find this issue in order to figure out what was happening. Does this behavior still make sense? If so, I think I'd like to make a note in the docs for this, it ate up quite a lot of time for me debugging this. I think another API that might be useful for this could be adding `params` as an option in `to_form`
