### ISSUE TITLE
Private hook `Phoenix.InfiniteScroll` is not applied after patch if phx-viewport-top and phx-viewport-bottom are not on the top level element

### ISSUE THREAD

**Issue by plondon** [phoenixframework/phoenix_live_view#2896] opened 2023-10-30 13:49 UTC
Hello and thank your great work on Phoenix Liveview!

### Environment

* Elixir version (elixir -v): 1.15.0
* Phoenix version (mix deps): 1.7.9
* Phoenix LiveView version (mix deps): 0.20.1
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

`Phoenix.InfiniteScroll` hook is not applied to element with phx-viewport-top and phx-viewport-bottom attributes if the element is a nested child.

https://github.com/plondon/paginate_infinite_scroll_patch

1. iex -S mix phx.server
2. run `DataMigration.migrate()` to add 100 posts
3. navigate to localhost:4000/paginate
4. notice pagination works on page load
5. navigate to Tab B
6. navigate to Tab A
7. **pagination does not work** <-- maybeAddPrivateHooks is called on the top level div, not the child

### Expected behavior
Apply `Phoenix.InfiniteScroll` hook to child divs on patch.

N.B if you remove the [top level div](https://github.com/plondon/paginate_infinite_scroll_patch/blob/master/lib/paginate_infinite_scroll_patch_web/live/paginate_component.ex#L10) pagination will work as expected between patches.

**Comment by SteffenDE** [comment] 2023-12-30 11:05
Duplicate of https://github.com/phoenixframework/phoenix_live_view/issues/2667, but your reproduction is more realistic 😃

**Closed** 2024-01-01 15:40 UTC
