### ISSUE TITLE
Radio button state is cleared when `phx-change` event sets assigns for disabled attribute in form submit button.

### ISSUE THREAD

**Issue by Skoda091** [phoenixframework/phoenix_live_view#1118] opened 2020-08-10 22:21 UTC
### Environment

* Elixir version (Elixir 1.10.3):
* Phoenix version (1.5.3):
* Phoenix LiveView version (0.13.0), (master):
* NodeJS version (v10.1.0):
* NPM version (6.14.5):
* Operating system: Mac OS Catalina
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari/Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: YES

### Actual behavior

When I use `phx-change` event to assign a variable that sets a disabled attribute for a form to submit button, the radio button state is cleared.

![bug_radio](https://user-images.githubusercontent.com/4904753/89836652-8b18e380-db67-11ea-815f-87bf6a0eec57.gif)

Form component template:
```elixir
<h2><%= @title %></h2>

<%= f = form_for @changeset, "#",
  id: "item-form",
  phx_target: @myself,
  phx_change: "validate",
  phx_submit: "save" %>

  <%= radio_button f, :name, "test"%><%= "Test" %>
  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= submit "Save", disabled: @disabled, phx_disable_with: "Saving..." %>
</form>
```
Form component module:
```elixir
defmodule ReproduceWeb.ItemLive.FormComponent do
 ...
  @impl true
  def update(%{item: item} = assigns, socket) do
    changeset = Resources.change_item(item)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:disabled, true)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"item" => item_params}, socket) do
    changeset =
      socket.assigns.item
      |> Resources.change_item(item_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("validate", _params, socket) do
    {:noreply, assign(socket, :disabled, false)}
  end
...
end
```
App to reproduce a bug: https://github.com/Skoda091/reproduce

### Expected behavior

Keep state of radio button whenever updating assigns on `phx-change` event.

**Comment by sfusato** [comment] 2020-08-11 16:31
You are passing the same field as for the `text_input` => `:name`:
```
<%= radio_button f, :name, "test"%><%= "Test" %>
<%= text_input f, :name %>
```

1. The radio button starts with value "test"
2. You click the radio button
3. `phx-change` event => the changeset gets validated
4. But since you use the same `:name` field as for the `text_input`, the new radio value will be empty string (`""`)
5. Thus, the radio state is cleared

If you change the `radio_button` field name to whatever else, it won't get cleared.

**Comment by josevalim** [comment] 2020-08-11 16:33
Closing per the reasons above!

@sfusato :green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Closed by josevalim** 2020-08-11 16:33 UTC

**Comment by Skoda091** [comment] 2020-08-11 19:04
@sfusato It doesn't change anything, even if there is only one radio button. The behavior is exactly the same.

**Comment by sfusato** [comment] 2020-08-12 06:24
That's strange.

![radio_button](https://user-images.githubusercontent.com/19363153/89981850-ea184e80-dc74-11ea-9358-2e94a5910d45.gif)

Can you please share your new `live/item_live/form_component.html.leex` or push a new commit with the changes to your repository?

**Comment by Skoda091** [comment] 2020-08-12 06:56
Sure
`live/item_live/form_component.html.leex`:
```elixir
<h2><%= @title %></h2>

<%= f = form_for @changeset, "#",
  id: "item-form",
  phx_target: @myself,
  phx_change: "validate",
  phx_submit: "save" %>

  <%= radio_button f, :name, "test"%><%= "Test" %>

  <%= submit "Save", disabled: @disabled, phx_disable_with: "Saving..." %>
</form>

```
It works in the same way even if I use `form_for` without changeset.

I've also pushed changes here: https://github.com/Skoda091/reproduce

**Comment by feliperenan** [comment] 2020-08-12 07:10
@Skoda091 it seems you are not putting your changes into your live view state, that your LV is not marked.

https://github.com/Skoda091/reproduce/blob/master/lib/reproduce_web/live/item_live/form_component.ex#L18

You should have something like this in order to update your changeset that is inside your LV state:

```Elixir
  @impl true
  def handle_event("validate", %{"item" => item_params}, socket) do
    changeset = Resources.change_item(socket.assigns.changeset, item_params)

    {:noreply,
     socket
     |> assign(:disabled, false)
     |> assign(:changeset, changeset)}
  end
```

**Comment by sfusato** [comment] 2020-08-12 08:57
Saving the state in the changeset works for me:
![radio_button_2](https://user-images.githubusercontent.com/19363153/89988762-4a60bd80-dc80-11ea-8453-db6c3546a26f.gif)

> Btw. In your example submit button is still disabled.

I was simply running your code. You weren't updating the `disabled` assign value in the `handle_info` callback previously.

**Comment by Skoda091** [comment] 2020-08-15 21:23
Is it possible to achieve that without using changeset in form? e.g
```elixir
<%= f = form_for :item, "#",
  id: "item-form",
  phx_target: @myself,
  phx_change: "validate",
  phx_submit: "save" %>
...
```

**Comment by feliperenan** [comment] 2020-08-17 07:06
If you have just one radio button you could do it without changeset as long as you set the value in the LV state and add it in the radio button. But I'd suggest you using changeset since it is easier to work with and you get all the power that changeset provides.

I like to use schemaless changeset in order to start simple when I don't have a schema for a specific form I'm building and I don't want to create one. Something like this:


```Elixir
  @search_form %{
    name: :integer
  }

  defp build_changeset(search_params) do
    fields = Map.keys(@search_form)

    Ecto.Changeset.cast({%{}, @search_form}, search_params, fields)
  end
```

If I see it is getting complex when new fields and validations start to appear, I probably move it to it own module as schema.
