### ISSUE TITLE
LiveView select fields cannot have options updated

### ISSUE THREAD

**Issue by dylantf** [phoenixframework/phoenix_live_view#2787] opened 2023-08-29 16:44 UTC
### Environment

* Elixir version (elixir -v): Elixir 1.14.4 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): phoenix 1.7.7 (Hex package) (mix)
  locked at 1.7.7 (phoenix) 8966e15c
* Phoenix LiveView version (mix deps): phoenix_live_view 0.19.5 (Hex package) (mix)
  locked at 0.19.5 (phoenix_live_view) b2eaa0dd
* Operating system: macos
* Browsers you attempted to reproduce this bug on (the more the merrier): chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Expected behavior

I would like to reset select box values and options when form values change or the form is submitted. The use case is with a cascading select, where the options in later fields depends on what is selected in previous fields. So when select1 is set, the value for select2 is cleared and options are set. When the form is submitted, all of the form values are cleared, and the options for select2 should be reset to `[]` (as select1 does not have a value).

### Actual behavior

The actual behavior is not predictable; I have found several different cases:
- With hardcoded options for both selects, the values are correctly cleared on submit.
- When the options for select2 are hardcoded but guaranteed to change every time (i.e. using a submit counter and flipping the options based on whether it's even or odd), the values are correctly cleared and the options update correctly.
- When select2 options are reset to an empty list, the value for select1 correctly clears but NOT select2 (the value is stuck). The options are also stuck and not cleared. Logging the assigns inside the render function indicates that the values and options are all correctly set, but the fields themselves do not update.

I did see the note about form bindings in the documentation:
> For any given input with focus, LiveView will never overwrite the input's current value, even if it deviates from the server's rendered updates. This works well for updates where major side effects are not expected, such as form validation errors, or additive UX around the user's input values as they fill out a form.

I added an additional text field to ensure the selects do not have focus when submitted.

Video example:

https://github.com/phoenixframework/phoenix_live_view/assets/3457993/955fe958-92a9-4acb-b6b4-035a1e7c9c09

Repository:
(Sorry I didn't see the one-file thing before I put this together)

https://github.com/dylantf/liveview_opts/blob/main/lib/lv_opts_web/live/demo_live.ex

Thanks to the Elixir Discord user Doughsay for helping me debug this and put together a simple example.

**Comment by josevalim** [comment] 2023-08-29 17:11
Does it work if you change the ID for the select input? I am almost sure this is intentional as to not change an input as a user may interact with it. But we need to better document it somewhere if not yet documented. Maybe in the JS interop guides.

**Comment by chrismccord** [comment] 2023-08-29 18:30
We don't overwrite any focused input's value, so in this case it's expected. Our docs could do a better job of explaining, but in the meantime you can roll the select input id when you need to update it while the user has focus

**Comment by doughsay** [comment] 2023-08-29 19:03
But in this case the select input has lost focus, no? The last input interacted with was the text input.

**Comment by dylantf** [comment] 2023-08-29 19:05
> We don't overwrite any focused input's value, so in this case it's expected. Our docs could do a better job of explaining, but in the meantime you can roll the select input id when you need to update it while the user has focus

When you say "focused input's value", do you actually mean any field that has user input? In my example there, the last field to have focus before clicking submit is the text field, so the 2nd select should still be updated, right? (Additionally, doesn't clicking a submit button put the focus on the button?)

Rotating the ID on submit does fix the issue. I just added a `submit_count` to assigns and set the input IDs to `id={"select2-#{@submit_count}"}` and it correctly clears when submitted now.

Since the selects clear correctly when the options are _NOT_ dynamic, I was assuming there was some issue with a rerender not being triggered correctly.

**Comment by AHBruns** [comment] 2023-12-04 18:41
@chrismccord, have you considered changing the semantics of inputs to rely on in-flight changes vs focus.

Basically, when an input triggers an event (e.g. phx-change or phx-submit), it enters an unsettled state. The input stays in an unsettled state until it has no more in-flight phx-change/phx-submit events at which time it moves back to a settled state. When in an unsettled state, the input tracks what value the server would have it show, but it doesn't actually show that value, instead it shows whatever the user's input is. When the input drops from an unsettled state back to a settled state, it render's the last value server the server sent it. You might call this eventually deterministic rendering. Only once the client is sure the server has "seen" the latest user input does render what the server tells it to.

This is how I've written my company's inputs to work, and it's been working great. Inputs update on the client instantly, but the server can still update fields without having to consider if they might currently be focused. My company is building a multiplayer form product which made the current focus based semantics untenable, but in building out inputs with these new semantics, I've come to believe they're a generally better approach for most applications (though they're admittedly much more complex to implement under the hood).

**Comment by SteffenDE** [comment] 2024-01-03 09:11
e5c6f78224e1b2558c0c3fd8a312dc79edb9849e changes the behaviour described in this issue, although it does not fix this. Now, even the first select does not reset. If I find the time, I might look into this a little bit more.

**Comment by SteffenDE** [comment] 2024-01-10 16:01
I just tested https://github.com/dylantf/liveview_opts/blob/main/lib/lv_opts_web/live/demo_live.ex with the latest main and https://github.com/phoenixframework/phoenix_live_view/commit/0d084243015c4f37c4d9cb054bdd87e82911e83f changes the behavior so that the second select is reset as one would expect. Still, the first select does not reset, even though the form is reassigned.

**Comment by chrismccord** [comment] 2024-01-10 20:11
The select issue is now fixed as reported in this issue (the 2nd select not clearing properly). For the first select, the issue is on the application side. You are not maintaining your form state on the server in your phx-update handle_event. You must maintain the values yourself and recast the changeset, which will re-render the form. The issue you are having is the assign in submit (`to_form(changeset(%{}), as: :demo),)` is exactly the same value you assign in mount for the form. This form assign never changes and then re-assigning on submit produces no diff, because the value didn't change, so it is not re-rendered on the server, and therefore not reset on the client. 

Your phx-update handler should look something like this:

```elixir
    {:noreply,
     assign(socket,
       select2_opts: select2_opts,
       form: to_form(changeset(demo_params), as: :demo)
     )}
```

Thanks!

**Closed by chrismccord** 2024-01-10 20:11 UTC
Labels: upnext
