### ISSUE TITLE
LiveView Channel crash when redirecting from Plug

### ISSUE THREAD

**Issue by jlauemoeller** [phoenixframework/phoenix_live_view#871] opened 2020-05-09 10:50 UTC
### Environment

* Elixir version (elixir -v): Elixir 1.9.4 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.5.1
* Phoenix LiveView version (mix deps): 0.12.1
* NodeJS version (node -v): v13.3.0
* NPM version (npm -v): 6.13.2
* Operating system: macOS 10.15.4, also seen on Ubuntu 18.04
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari 13.1, Chrome 81.0.4044.138, Firefox 76.0
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Assume that the user is viewing `/` and clicks a link to `/protected`. A plug intercepts the request and determines that the user must be logged in to access `/protected`  and thus redirects to `/login`, e.g.:

```elixir
defmodule RedirectWeb.RequireUser do

  alias RedirectWeb.Router.Helpers, as: Routes

  def init(opts), do: opts

  def call(conn, _opts) do
    case Plug.Conn.get_session(conn, :current_user_id) do
      nil ->
        login = Routes.login_path(RedirectWeb.Endpoint, :index, %{continue_at: conn.request_path})

        conn
        |> Phoenix.Controller.redirect(to: login)
        |> Plug.Conn.halt

      _ ->
        conn
    end
  end
end
```

During this redirect, the LiveView Channel crashes when the browser tries to join the LiveView that was redirected to (e.g. `LoginLive`). 

As far as I can tell, this happens because the LiveView socket still has the `/protected` url in its endpoint structure, that is, the url that was requested and led to the redirect, but the join correctly tries to reach the LiveView associated with the URL that was redirected to.

This leads to a situation in `Phoenix.LiveView.Channel.verified_mount` where the LiveView and URL doesn't match and this crashes the channel.

### Expected behavior

The LiveView channel should not crash and the URL and LiveView module should match.

### Repo That reproduces Issue

Please see https://github.com/jlauemoeller/liveview_redirect_crash for a repo that reproduces the issue. The repo was generated with `mix phx.new --live --no-ecto` and the following files added:

* lib/redirect_web/require_user.ex
* lib/redirect_web/login_live.ex
* lib/redirect_web/protected_live.ex
* lib/redirect_web/session_controller.ex

Additionally the router was updated with `live` macros to each of the LiveViews.

### Log Output
Below is a slightly instrumented log output generated by the code in the repo mentioned above. I have added extra logging in PoolSupervisor and Phoenix.LiveView.Channel that output selected parameters (the repo README.md contains log output without extra tracing). 

The trace starts when the user clicks `/protected` from `/` (`PageLive`).

```
[info] GET /protected
[debug] Processing with Phoenix.LiveView.Plug.index/2
  Parameters: %{}
  Pipelines: [:browser, :require_user]
[info] Sent 302 in 241µs
[info] GET /login
[debug] Processing with Phoenix.LiveView.Plug.index/2
  Parameters: %{"continue_at" => "/protected"}
  Pipelines: [:browser]
[info] Sent 200 in 310µs
[info] PoolSupervisor.start_child({RedirectWeb.Endpoint, Phoenix.LiveView.Socket, {#PID<0.640.0>, #Reference<0.784644094.1128005641.185954>}, %{id: Phoenix.LiveView.Channel, restart: :temporary, start: {Phoenix.LiveView.Channel, :start_link, [{%{"joins" => 0, "params" => %{"_csrf_token" => "IDV3Ez8oHQJODG44FDwUGhh_GUQwHWZkdeNzKjOo8X4wrRAXQMQ1aP5S"}, "session" => "SFMyNTY.g2gDaAJhBHQAAAAHZAACaWRtAAAAFHBoeC1GZzFUQ2x4Tk9DQ25QQXNHZAAKcGFyZW50X3BpZGQAA25pbGQACHJvb3RfcGlkZAADbmlsZAAJcm9vdF92aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZWQABnJvdXRlcmQAGUVsaXhpci5SZWRpcmVjdFdlYi5Sb3V0ZXJkAAdzZXNzaW9udAAAAABkAAR2aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZW4GAOeS0_hxAWIAAVGA.3LECIWxAUKLtAjkKW0M0TvXrJ5FOIw3VbnzAqmYJnIg", "static" => nil, "url" => "http://localhost:4000/protected"}, {#PID<0.640.0>, #Reference<0.784644094.1128005641.185954>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.Channel, channel_pid: nil, endpoint: RedirectWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: nil, join_ref: "8", joined: false, private: %{session: %{"_csrf_token" => "DP9itBRmvTZOfnUBI2HuQMS7"}}, pubsub_server: Redirect.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lv:phx-Fg1TClxNOCCnPAsG", transport: :websocket, transport_pid: #PID<0.640.0>}}]}}}
[info] Channel.start_link(%{"joins" => 0, "params" => %{"_csrf_token" => "IDV3Ez8oHQJODG44FDwUGhh_GUQwHWZkdeNzKjOo8X4wrRAXQMQ1aP5S"}, "session" => "SFMyNTY.g2gDaAJhBHQAAAAHZAACaWRtAAAAFHBoeC1GZzFUQ2x4Tk9DQ25QQXNHZAAKcGFyZW50X3BpZGQAA25pbGQACHJvb3RfcGlkZAADbmlsZAAJcm9vdF92aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZWQABnJvdXRlcmQAGUVsaXhpci5SZWRpcmVjdFdlYi5Sb3V0ZXJkAAdzZXNzaW9udAAAAABkAAR2aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZW4GAOeS0_hxAWIAAVGA.3LECIWxAUKLtAjkKW0M0TvXrJ5FOIw3VbnzAqmYJnIg", "static" => nil, "url" => "http://localhost:4000/protected"}, ..., ...)
[info] verified_mount: router = RedirectWeb.Router
[info] verified_mount: url    = "http://localhost:4000/protected"
[info] verified_mount: view   = RedirectWeb.LoginLive
[info] verified_mount: live_link_info = :external
[error] GenServer #PID<0.655.0> terminating
** (RuntimeError) cannot invoke handle_params/3 for RedirectWeb.LoginLive because RedirectWeb.LoginLive was not mounted at the router with the live/3 macro under URL "http://localhost:4000/protected"
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:211: Phoenix.LiveView.Channel.maybe_call_mount_handle_params/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:634: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:38: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
State: {%{"joins" => 0, "params" => %{"_csrf_token" => "IDV3Ez8oHQJODG44FDwUGhh_GUQwHWZkdeNzKjOo8X4wrRAXQMQ1aP5S"}, "session" => "SFMyNTY.g2gDaAJhBHQAAAAHZAACaWRtAAAAFHBoeC1GZzFUQ2x4Tk9DQ25QQXNHZAAKcGFyZW50X3BpZGQAA25pbGQACHJvb3RfcGlkZAADbmlsZAAJcm9vdF92aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZWQABnJvdXRlcmQAGUVsaXhpci5SZWRpcmVjdFdlYi5Sb3V0ZXJkAAdzZXNzaW9udAAAAABkAAR2aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZW4GAOeS0_hxAWIAAVGA.3LECIWxAUKLtAjkKW0M0TvXrJ5FOIw3VbnzAqmYJnIg", "static" => nil, "url" => "http://localhost:4000/protected"}, {#PID<0.640.0>, #Reference<0.784644094.1128005641.185954>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.Channel, channel_pid: nil, endpoint: RedirectWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: nil, join_ref: "8", joined: false, private: %{session: %{"_csrf_token" => "DP9itBRmvTZOfnUBI2HuQMS7"}}, pubsub_server: Redirect.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lv:phx-Fg1TClxNOCCnPAsG", transport: :websocket, transport_pid: #PID<0.640.0>}}
[error] an exception was raised:
    ** (RuntimeError) cannot invoke handle_params/3 for RedirectWeb.LoginLive because RedirectWeb.LoginLive was not mounted at the router with the live/3 macro under URL "http://localhost:4000/protected"
        (phoenix_live_view) lib/phoenix_live_view/channel.ex:211: Phoenix.LiveView.Channel.maybe_call_mount_handle_params/4
        (phoenix_live_view) lib/phoenix_live_view/channel.ex:634: Phoenix.LiveView.Channel.verified_mount/4
        (phoenix_live_view) lib/phoenix_live_view/channel.ex:38: Phoenix.LiveView.Channel.handle_info/2
        (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
[info] PoolSupervisor.start_child({RedirectWeb.Endpoint, Phoenix.LiveView.Socket, {#PID<0.640.0>, #Reference<0.784644094.1128005634.183049>}, %{id: Phoenix.LiveView.Channel, restart: :temporary, start: {Phoenix.LiveView.Channel, :start_link, [{%{"joins" => 0, "params" => %{"_csrf_token" => "IDV3Ez8oHQJODG44FDwUGhh_GUQwHWZkdeNzKjOo8X4wrRAXQMQ1aP5S"}, "session" => "SFMyNTY.g2gDaAJhBHQAAAAHZAACaWRtAAAAFHBoeC1GZzFUQ2x4Tk9DQ25QQXNHZAAKcGFyZW50X3BpZGQAA25pbGQACHJvb3RfcGlkZAADbmlsZAAJcm9vdF92aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZWQABnJvdXRlcmQAGUVsaXhpci5SZWRpcmVjdFdlYi5Sb3V0ZXJkAAdzZXNzaW9udAAAAABkAAR2aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZW4GAOeS0_hxAWIAAVGA.3LECIWxAUKLtAjkKW0M0TvXrJ5FOIw3VbnzAqmYJnIg", "static" => nil, "url" => "http://localhost:4000/protected"}, {#PID<0.640.0>, #Reference<0.784644094.1128005634.183049>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.Channel, channel_pid: nil, endpoint: RedirectWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: nil, join_ref: "9", joined: false, private: %{session: %{"_csrf_token" => "DP9itBRmvTZOfnUBI2HuQMS7"}}, pubsub_server: Redirect.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lv:phx-Fg1TClxNOCCnPAsG", transport: :websocket, transport_pid: #PID<0.640.0>}}]}}}
[info] Channel.start_link(%{"joins" => 0, "params" => %{"_csrf_token" => "IDV3Ez8oHQJODG44FDwUGhh_GUQwHWZkdeNzKjOo8X4wrRAXQMQ1aP5S"}, "session" => "SFMyNTY.g2gDaAJhBHQAAAAHZAACaWRtAAAAFHBoeC1GZzFUQ2x4Tk9DQ25QQXNHZAAKcGFyZW50X3BpZGQAA25pbGQACHJvb3RfcGlkZAADbmlsZAAJcm9vdF92aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZWQABnJvdXRlcmQAGUVsaXhpci5SZWRpcmVjdFdlYi5Sb3V0ZXJkAAdzZXNzaW9udAAAAABkAAR2aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZW4GAOeS0_hxAWIAAVGA.3LECIWxAUKLtAjkKW0M0TvXrJ5FOIw3VbnzAqmYJnIg", "static" => nil, "url" => "http://localhost:4000/protected"}, ..., ...)
[info] verified_mount: router = RedirectWeb.Router
[info] verified_mount: url    = "http://localhost:4000/protected"
[info] verified_mount: view   = RedirectWeb.LoginLive
[info] verified_mount: live_link_info = :external
[error] GenServer #PID<0.656.0> terminating
** (RuntimeError) cannot invoke handle_params/3 for RedirectWeb.LoginLive because RedirectWeb.LoginLive was not mounted at the router with the live/3 macro under URL "http://localhost:4000/protected"
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:211: Phoenix.LiveView.Channel.maybe_call_mount_handle_params/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:634: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:38: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
State: {%{"joins" => 0, "params" => %{"_csrf_token" => "IDV3Ez8oHQJODG44FDwUGhh_GUQwHWZkdeNzKjOo8X4wrRAXQMQ1aP5S"}, "session" => "SFMyNTY.g2gDaAJhBHQAAAAHZAACaWRtAAAAFHBoeC1GZzFUQ2x4Tk9DQ25QQXNHZAAKcGFyZW50X3BpZGQAA25pbGQACHJvb3RfcGlkZAADbmlsZAAJcm9vdF92aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZWQABnJvdXRlcmQAGUVsaXhpci5SZWRpcmVjdFdlYi5Sb3V0ZXJkAAdzZXNzaW9udAAAAABkAAR2aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZW4GAOeS0_hxAWIAAVGA.3LECIWxAUKLtAjkKW0M0TvXrJ5FOIw3VbnzAqmYJnIg", "static" => nil, "url" => "http://localhost:4000/protected"}, {#PID<0.640.0>, #Reference<0.784644094.1128005634.183049>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.Channel, channel_pid: nil, endpoint: RedirectWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: nil, join_ref: "9", joined: false, private: %{session: %{"_csrf_token" => "DP9itBRmvTZOfnUBI2HuQMS7"}}, pubsub_server: Redirect.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lv:phx-Fg1TClxNOCCnPAsG", transport: :websocket, transport_pid: #PID<0.640.0>}}
[error] an exception was raised:
    ** (RuntimeError) cannot invoke handle_params/3 for RedirectWeb.LoginLive because RedirectWeb.LoginLive was not mounted at the router with the live/3 macro under URL "http://localhost:4000/protected"
        (phoenix_live_view) lib/phoenix_live_view/channel.ex:211: Phoenix.LiveView.Channel.maybe_call_mount_handle_params/4
        (phoenix_live_view) lib/phoenix_live_view/channel.ex:634: Phoenix.LiveView.Channel.verified_mount/4
        (phoenix_live_view) lib/phoenix_live_view/channel.ex:38: Phoenix.LiveView.Channel.handle_info/2
        (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
[info] GET /protected
[debug] Processing with Phoenix.LiveView.Plug.index/2
  Parameters: %{}
  Pipelines: [:browser, :require_user]
[info] Sent 302 in 233µs
[info] GET /login
[debug] Processing with Phoenix.LiveView.Plug.index/2
  Parameters: %{"continue_at" => "/protected"}
  Pipelines: [:browser]
[info] Sent 200 in 569µs
[info] CONNECTED TO Phoenix.LiveView.Socket in 167µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "diJPPBh1FB06FgwFEB49MD9dOx9lJjlC2rvUl7FpLBVJvphrvosj4kju", "vsn" => "2.0.0"}
[info] PoolSupervisor.start_child({RedirectWeb.Endpoint, Phoenix.LiveView.Socket, {#PID<0.668.0>, #Reference<0.784644094.1128005634.183674>}, %{id: Phoenix.LiveView.Channel, restart: :temporary, start: {Phoenix.LiveView.Channel, :start_link, [{%{"joins" => 0, "params" => %{"_csrf_token" => "diJPPBh1FB06FgwFEB49MD9dOx9lJjlC2rvUl7FpLBVJvphrvosj4kju"}, "session" => "SFMyNTY.g2gDaAJhBHQAAAAHZAACaWRtAAAAFHBoeC1GZzFUQ3JMYWFsQWFyZ1JDZAAKcGFyZW50X3BpZGQAA25pbGQACHJvb3RfcGlkZAADbmlsZAAJcm9vdF92aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZWQABnJvdXRlcmQAGUVsaXhpci5SZWRpcmVjdFdlYi5Sb3V0ZXJkAAdzZXNzaW9udAAAAABkAAR2aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZW4GAJOY0_hxAWIAAVGA.0J17Ced2uQLD9KNbtSX9_OJH8LBrBsSyu27blQHaHCY", "static" => "SFMyNTY.g2gDaAJhBHQAAAADZAAKYXNzaWduX25ld2pkAAVmbGFzaHQAAAAAZAACaWRtAAAAFHBoeC1GZzFUQ3JMYWFsQWFyZ1JDbgYAk5jT-HEBYgABUYA.5wfYiXC7g0q4Da-9TkzzonTcvzhC70QMfv9TAt4eXOc", "url" => "http://localhost:4000/login?continue_at=%2Fprotected"}, {#PID<0.668.0>, #Reference<0.784644094.1128005634.183674>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.Channel, channel_pid: nil, endpoint: RedirectWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: nil, join_ref: "4", joined: false, private: %{session: %{"_csrf_token" => "DP9itBRmvTZOfnUBI2HuQMS7"}}, pubsub_server: Redirect.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lv:phx-Fg1TCrLaalAargRC", transport: :websocket, transport_pid: #PID<0.668.0>}}]}}}
[info] Channel.start_link(%{"joins" => 0, "params" => %{"_csrf_token" => "diJPPBh1FB06FgwFEB49MD9dOx9lJjlC2rvUl7FpLBVJvphrvosj4kju"}, "session" => "SFMyNTY.g2gDaAJhBHQAAAAHZAACaWRtAAAAFHBoeC1GZzFUQ3JMYWFsQWFyZ1JDZAAKcGFyZW50X3BpZGQAA25pbGQACHJvb3RfcGlkZAADbmlsZAAJcm9vdF92aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZWQABnJvdXRlcmQAGUVsaXhpci5SZWRpcmVjdFdlYi5Sb3V0ZXJkAAdzZXNzaW9udAAAAABkAAR2aWV3ZAAcRWxpeGlyLlJlZGlyZWN0V2ViLkxvZ2luTGl2ZW4GAJOY0_hxAWIAAVGA.0J17Ced2uQLD9KNbtSX9_OJH8LBrBsSyu27blQHaHCY", "static" => "SFMyNTY.g2gDaAJhBHQAAAADZAAKYXNzaWduX25ld2pkAAVmbGFzaHQAAAAAZAACaWRtAAAAFHBoeC1GZzFUQ3JMYWFsQWFyZ1JDbgYAk5jT-HEBYgABUYA.5wfYiXC7g0q4Da-9TkzzonTcvzhC70QMfv9TAt4eXOc", "url" => "http://localhost:4000/login?continue_at=%2Fprotected"}, ..., ...)
[info] verified_mount: router = RedirectWeb.Router
[info] verified_mount: url    = "http://localhost:4000/login?continue_at=%2Fprotected"
[info] verified_mount: view   = RedirectWeb.LoginLive
[info] verified_mount: live_link_info = {:internal, %{"continue_at" => "/protected"}, :index, %URI{authority: "localhost:4000", fragment: nil, host: "localhost", path: "/login", port: 4000, query: "continue_at=%2Fprotected", scheme: "http", userinfo: nil}}
[info] PoolSupervisor.start_child({RedirectWeb.Endpoint, Phoenix.LiveReloader.Socket, {#PID<0.672.0>, #Reference<0.784644094.1128005638.182967>}, %{id: Phoenix.LiveReloader.Channel, restart: :temporary, shutdown: 5000, start: {Phoenix.LiveReloader.Channel, :start_link, [{%{}, {#PID<0.672.0>, #Reference<0.784644094.1128005638.182967>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveReloader.Channel, channel_pid: nil, endpoint: RedirectWeb.Endpoint, handler: Phoenix.LiveReloader.Socket, id: nil, join_ref: "3", joined: false, private: %{}, pubsub_server: Redirect.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "phoenix:live_reload", transport: :websocket, transport_pid: #PID<0.672.0>}}]}}}

```

**Comment by josevalim** [comment] 2020-05-09 11:57
Thank you @jlauemoeller for the extremely detailed report. I could reproduce the issue locally. The issue seems to be related to live_redirect. If we are live redirecting to something that returns a non-200, we are still attempting to connect.

This can also be a race-condition on the client: because we do ask the browser to redirect but maybe other actions continue happening until the browser effectively does it.

**Comment by jlauemoeller** [comment] 2020-05-10 20:10
Thanks for taking time out to look at this - much appreciated!

I have managed to crawl a bit further down the rabbit hole and notice that the problem starts when (in the client), `Browser.replaceMain()` tries to join the root view:

```javascript
Browser.fetchPage(href, (status, html) => {
   ...
   this.joinRootView(el, href, flash, (newMain, joinCount) => {
     if(joinCount !== 1){ return }
     if(!this.commitPendingLink(linkRef)){
       newMain.destroy()
       return
     }
     mainEl.replaceWith(newMain.el)
     this.main = newMain
     callback && callback()
   })
})
```

At this point `href` will be the originally requested resource (e.g. `/protected`) but `html` will be similar to `<div data-phx-session="..." phx-view="LoginView" ...></div>` which I suppose is emitted by `Phoenix.LiveView.Plug.call/2` when it detects that a `live_link?` request is in effect. 

This causes the join to crash because the `href` and the view doesn't match.

So, why the mismatch? I think what happens is roughly this:

The user clicks on the link and the "click" event handler initiates a `historyRedirect`:

```javascript
...
  } else if(type === "redirect") {
     this.historyRedirect(href, linkState)
  }
...
```

This causes `Browser.fetchPage` to set up an `XMLHttpRequest` for `/protected`. However, since my `RequireUser` plug sends a redirect back, the `XMLHttpRequest` will follow this and request the `/login` resource as indicated in the location header returned by the redirect response. 

When the `XMLHttpRequest` finally reaches ready state 4 after the redirect and invokes the callback supplied by `Browser.replaceMain`, the contents of the response is the live-link snippet sent back by `Phoenix.LiveView.Plug.call/2`, yet the `href` used by the callback (which it gets from the `replaceMain` closure) is still `/protected`.

In other words; we hold on to the originally requested URL in `href` but because of the redirect that happens while requesting it, receive a live-link snippet with a view module corresponding to the URL that was redirected to.

I think we should use `req.reponseURL` supplied to the `onreadystatechange` callback instead, e.g.:

```javascript
  req.onreadystatechange = () => {
     if(req.readyState !== 4){ return }
     if(req.getResponseHeader(LINK_HEADER) !== "live-link"){ return callback(400) }
     if(req.status !== 200){ return callback(req.status) }
==>  callback(200, new URL(req.responseURL), req.responseText)
  }
```

and then in the `replaceMain` callback:

```javascript
...
   Browser.fetchPage(href, (status, url, html) => {
   ...
==>  let location = url.origin + url.pathname

==>  this.joinRootView(el, location, flash, (newMain, joinCount) => {
      ...
   })
...
```

This solves the issue and avoids crashing the channel since the supplied url and the view module now matches, even after redirects.

I would be happy to make a pull request with these changes if you agree that it is the right solution.

**Comment by chrismccord** [comment] 2020-05-13 14:32
Thank you for the detailed repro and the PR! It turns out IE does not support the `responseURL` attribute of `XMLHTTPRequest`, so I had to make changes on the server to accommodate this fact. Fixed on master!

**Closed by chrismccord** 2020-05-13 14:32 UTC

**Comment by jlauemoeller** [comment] 2020-05-13 14:51
Cool, thank you for getting this fixed so quickly!
