### ISSUE TITLE
`push_patch/2` with `replace: true` option doesn't change URL correctly

### ISSUE THREAD

**Issue by nallwhy** [phoenixframework/phoenix_live_view#2615] opened 2023-05-04 14:51 UTC
### Environment

* Elixir version (elixir -v): 1.14.2
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): 0.18.18
* Operating system: Mac OS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

1. from this page https://json.media/blog/how_elixir_became_a_mature_language_in_less_than_10_years
2. click `Back to posts`
3. URL changed to `https://json.media/blog?test=1`
4. URL changed to `https://json.media/blog` immediately <-- bug

code

```elixir
...
  @impl true
  def handle_params(params, _uri, socket) do
    socket = socket |> reset_assigns()
  
    socket =
      case params["test"] do
        nil ->
          socket
          |> push_patch(to: ~p"/blog?test=1", replace: true)
  
        _ ->
          socket
      end
  
    {:noreply, socket}
  end
...
```

https://github.com/nallwhy/json_corp/commit/7714018e2e7d388c3b7bb44fd61ec18cf5233c3b

It only happens when changing page **between liveviews in the same live session**.

For example,
1. from this page https://json.media/playgrounds
2. click `GO TO BLOG` button
3. URL changed to `https://json.media/blog?test=1`

```elixir
  scope "/blog", JsonCorpWeb.Blog, as: :blog do
    pipe_through :browser

    live_session :blog,
      on_mount: [
        JsonCorpWeb.SessionHook,
        JsonCorpWeb.ViewLogHook
      ] do
      live "/", PostLive.Index, :index
      live "/:slug", PostLive.Show, :show
    end
  end

  scope "/playgrounds", JsonCorpWeb.Playgrounds, as: :playgrounds do
    pipe_through :browser

    live_session :playground, on_mount: [JsonCorpWeb.SessionHook] do
      live "/", PlaygroundLive
      live "/form", FormLive
      live "/chat", ChatLive
    end
  end
```

https://github.com/nallwhy/json_corp/blob/push_patch_replace_bug/apps/json_corp_web/lib/json_corp_web/router.ex

### Expected behavior

1. from this page https://json.media/blog/how_elixir_became_a_mature_language_in_less_than_10_years
4. click `Back to posts`
3. URL changed to `https://json.media/blog?test=1`

**Comment by nallwhy** [comment] 2023-05-04 23:23
> You can only do `push_patch` within the same LiveView instance. Otherwise you must use `push_navigate`. We do have a fallback if you try to patch to a different LiveView and perhaps we are "losing" the parameters when we invoke the fallback. If that's the case, we should fix that.

I do `push_patch` within the same LiveView instance.
It is to use `push_patch/2` to apply the default parameters when LiveView is accessed.

LiveViewA -> push_patch -> LiveViewA with default parameter.

**Comment by enewbury** [comment] 2023-07-14 17:21
@nallwhy I'm not sure about your situation exactly without the entire code, but one thing to consider is that `mount` and `handle_params` is called once initially for the static page load, and then called again once the socket connects.
In my liveview sandbox, I'm seeing that query params are not set on the initial call of handle_params that renders the static page. I'm not sure why that is, maybe one of the maintainers can chime in on that. However, calling `push_patch` in `handle_params` caused an infinite loop for me because is didn't recognize that it was already redirected to the right page because it wasn't receiving the query params in callback.
Wrapping the `push_patch` in an `if connected?(socket)` solves it for my example. I'm attaching my example code. If you're still seeing issues, perhaps you could modify this single-file example to reproduce your issue?
```elixir
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7.0"},
  {:phoenix_live_view, "~> 0.19.0"}
])

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.HomeLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  use Phoenix.VerifiedRoutes,
    router: Example.Router,
    endpoint: Example.Endpoint

  def mount(params, _session, socket) do
    IO.inspect(params, label: "PARAMS IN MOUNT")
    {:ok, assign(socket, :value, nil)}
  end

  defp phx_vsn, do: Application.spec(:phoenix, :vsn)
  defp lv_vsn, do: Application.spec(:phoenix_live_view, :vsn)

  def render("live.html", assigns) do
    ~H"""
    <script src={"https://cdn.jsdelivr.net/npm/phoenix@#{phx_vsn()}/priv/static/phoenix.min.js"}></script>
    <script src={"https://cdn.jsdelivr.net/npm/phoenix_live_view@#{lv_vsn()}/priv/static/phoenix_live_view.min.js"}></script>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }
    </style>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""
    Test Param: <%= @value %>
    """
  end

  def handle_params(%{"test" => value} = params, _uri, socket) do
    {:noreply, assign(socket, :value, value)}
  end

  def handle_params(params, uri, socket) do
    if connected?(socket) do
      {:noreply, push_patch(socket, to: ~p"/home?test=1", replace: true)}
    else
      {:noreply, socket}
    end
  end
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/home", HomeLive, :index)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)
  plug(Example.Router)
end

{:ok, _} = Supervisor.start_link([Example.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)

```

**Comment by enewbury** [comment] 2023-07-14 21:23
https://github.com/phoenixframework/phoenix_live_view/blob/13a17522881bc1d16c5a9c7d69519c5debcebbc0/assets/js/phoenix_live_view/live_socket.js#L777-L783

https://github.com/phoenixframework/phoenix_live_view/blob/13a17522881bc1d16c5a9c7d69519c5debcebbc0/assets/js/phoenix_live_view/live_socket.js#L404-L412

Looks like this is caused because the "navigate" handler commits the pending url change, and then runs the browser history push inside of `requestAnimationFrame`, and in the meantime, the "live_patch" event comes in, sees that there is no pending url, and makes the update. Then the callback runs for the original navigate, and overwrites the url back to the original non-redirected endpoint.

**Comment by zachdaniel** [comment] 2023-08-02 22:24
I'm seeing this happen in my application even with the fix linked above.

**Comment by SteffenDE** [comment] 2024-01-20 12:12
I tried to reproduce what @nallwhy initially reported, but this seems to work just fine now.

```
Application.put_env(:sample, Example.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 5001],
  server: true,
  live_view: [signing_salt: "aaaaaaaa"],
  secret_key_base: String.duplicate("a", 64)
)

Mix.install([
  {:plug_cowboy, "~> 2.5"},
  {:jason, "~> 1.0"},
  {:phoenix, "~> 1.7.10", override: true},
  {:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "main"}
  # {:phoenix_live_view, path: "./oss/phoenix_live_view"}
])

defmodule Example.ErrorView do
  def render(template, _), do: Phoenix.Controller.status_message_from_template(template)
end

defmodule Example.HomeLive do
  use Phoenix.LiveView, layout: {__MODULE__, :live}

  def mount(params, _session, socket) do
    socket
    |> then(&{:ok, &1})
  end

  def handle_params(params, uri, socket) do
    socket =
      case params["test"] do
        nil ->
          socket
          |> push_patch(to: "/?test=1", replace: true)

        _ ->
          socket
      end

    {:noreply, socket}
  end

  def render("live.html", assigns) do
    ~H"""
    <script src="https://cdn.jsdelivr.net/npm/phoenix@1.7.10/priv/static/phoenix.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/phoenixframework/phoenix_live_view@main/priv/static/phoenix_live_view.js"></script>
    <%!-- <script src="http://127.0.0.1:8000/priv/static/phoenix_live_view.js"></script> --%>
    <script>
      let liveSocket = new window.LiveView.LiveSocket("/live", window.Phoenix.Socket)
      liveSocket.connect()
    </script>
    <style>
      * { font-size: 1.1em; }
    </style>
    <%= @inner_content %>
    """
  end

  def render(assigns) do
    ~H"""
    <h1>Hello</h1>

    <.link patch={"/"}>Link to /</.link>
    """
  end
end

defmodule Example.Router do
  use Phoenix.Router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug(:accepts, ["html"])
  end

  scope "/", Example do
    pipe_through(:browser)

    live("/", HomeLive, :index)
  end
end

defmodule Example.Endpoint do
  use Phoenix.Endpoint, otp_app: :sample
  socket("/live", Phoenix.LiveView.Socket)

  plug(Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()
  )

  plug(Example.Router)
end

{:ok, _} = Supervisor.start_link([Example.Endpoint], strategy: :one_for_one)
Process.sleep(:infinity)
```

@zachdaniel If you're able to provide a minimal example to reproduce, I'd be happy to take another look.

**Comment by pecampelo** [comment] 2024-01-23 13:31
I have an application in production utilizing the same approach of getting the parameters through a search, and updating the url. After updating LiveView to 0.20.0+, this feature has not seemed to work anymore. Until this is fixed, I have altered it to `push_redirect`, which seems to work.

**Comment by chrismccord** [comment] 2024-01-23 14:06
@pecampelo please try main and report back. We have closed out a bunch of issues recently and since we can't recreate ourselves we need more info. Thanks!

**Comment by pecampelo** [comment] 2024-01-23 20:26
@chrismccord, my issue has been solved. Apparently, what happened was that I mistakingly updated Phoenix and LiveView  to main (LiveView 0.20.+) , but did not update them in `/assets/package.json`, and therefore some differences were making `push_patch` not replace in any way, even though the parameters were correct in a second `handle_params` callback. For me, then, the issue on my end seems to be solved.

**Comment by SteffenDE** [comment] 2024-01-23 20:59
I think we can close this for now. If someone can still reproduce this, feel free to reopen or just open a new issue. Thank you!

**Closed by SteffenDE** 2024-01-23 20:59 UTC
Labels: awaiting feedback

**Comment by nallwhy** [comment] 2024-02-02 00:43
I can't reproduce this bug in the current version. Thanks!
