### ISSUE TITLE
Form errors not displaying when only one field has been touched

### ISSUE THREAD

**Issue by achedeuzot** [phoenixframework/phoenix_live_view#1135] opened 2020-09-05 08:56 UTC
### Environment

* Elixir version (elixir -v): 
   ```
   Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
   Elixir 1.10.2 (compiled with Erlang/OTP 21)
   ```
* Phoenix version (mix deps):
* Phoenix LiveView version (mix deps):
  ```
  * phoenix 1.5.4 (Hex package) (mix)
  locked at 1.5.4 (phoenix) 4e516d13
  ok
  * phoenix_live_view 0.13.3 (Hex package) (mix)
  locked at 0.13.3 (phoenix_live_view) c6309a7d
  ok
  ```
* NodeJS version (node -v): `v8.3.0`
* NPM version (npm -v): `5.3.0`
* Operating system: MacOS Catalina – 10.15.6 (19G2021)
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome 85, Firefox 80.0.1
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

The form validation errors are sometimes not displayed.

- When submitting an empty form -> OK, the field errors are shown (see screen recording (4 seconds) https://www.dropbox.com/s/k7qkqv7exvqewd7/Empty_form_OK.mp4?dl=0 )
- When submitting after entering information into one (1) field, the field errors are not shown (the `phx-no-feedback` class is still present). If I change anything (type a letter, check a checkbox, etc.) then all the errors are shown at once. (see screen recording (19 seconds) https://www.dropbox.com/s/w92et15anfl6vwr/Form_one_text_field_error.mp4?dl=0 )

Here is a sample app that reproduces the behaviour: https://github.com/achedeuzot/formerror and the sample form is at the URL http://127.0.0.1:4000/formerror 

### Expected behavior

I would expect that the form shows errors after all submits, without needing to change a field to re-trigger an update/validation.

**Comment by feliperenan** [comment] 2020-11-02 21:17
Hi 👋 

It seems that Live View can't track changes your changeset when it is invalid because you are updating the action with `insert`.

https://github.com/achedeuzot/formerror/blob/master/lib/formerrors_web/live/step1.ex#L40

If you change to `Map.put_changeset(changeset, :action, :validate)` it is supposed to work as you are expecting. BTW, that is how generator would generate the form for you, so it works as expected.

https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.live/form_component.ex#L21

I believe we can close this one 🙌

**Comment by josevalim** [comment] 2020-11-02 21:51
Setting it to `insert` should work but the issue is that you are discarding the updated changeset with errors:

https://github.com/achedeuzot/formerror/blob/master/lib/formerrors_web/live/step1.ex#L36

If you change it to 

    {:error, changeset}

Then it will should work too. I think setting it to validate also worked because at least it is a different action than the other branch.

**Comment by josevalim** [comment] 2020-11-02 21:51
Thanks for looking into this @feliperenan and providing the clue to where the mistake was! :heart:

**Closed by josevalim** 2020-11-02 21:51 UTC

**Comment by achedeuzot** [comment] 2020-11-13 13:41
Hello @feliperenan and @josevalim and thanks for looking into it.

I've just had the time to update my sample app:
- I replaced `:action`s with `:validate` instead of `:insert`. 
- I added the `changeset` back into the error (that was a silly mistake...)

Still, the same behavior persists.

Therefore, I've updated `phoenix_live_view` to the latest version (0.14.8), as well as my Elixir version (1.11.1) just in case. Unfortunately, it still doesn't change anything in this behavior.

I've started looking into the JS side to see if I can pinpoint where this is coming from and I think I have a lead:
When I enter data into one or more input fields, immediately after submitting, the `PHX_HAS_SUBMITTED` remains `undefined`(!). Then any field I touch will switch the value of this attribute to `true`, thus triggering the display of all the errors. I'm still unsure why `PHX_HAS_SUBMITTED` is `undefined` after a submit and needs at least one input before being set to `true`.

**Comment by justincjohnson** [comment] 2020-11-13 17:50
I'm not sure if this is directly related, but see #1166 for a similar issue I submitted.

**Comment by achedeuzot** [comment] 2020-11-13 18:12
> I'm not sure if this is directly related, but see #1166 for a similar issue I submitted.

Hi @justincjohnson, indeed, your description seems to be similar to the issue I'm describing. Also, I tried changing the liveview JS code with your fix but the same error persists. The `PHX_HAS_SUBMITTED` remains `undefined` even though the form has been submitted.

**Comment by achedeuzot** [comment] 2020-11-25 16:17
I upgraded to 0.15.0 and I'm still seeing this error. Any chance this issue could be reopened ? I've updated the `formerror` test repo to reproduce the issue.

**Comment by achedeuzot** [comment] 2020-11-27 10:16
In case someone else stumbles on this, I found the solution to this issue: it looks like on a form submit, the `:action` to use when sending the changeset has to be set to `:insert`. I was using `:action` set to `:validate` even on a submit and it was causing this behavior. As soon as set the action to `:insert` (even though it's a simple form with no backend), the form errors showed as expected.

I'll see if I can find some time to suggest an update to the docs about this and make it more explicit. 😄
